In [1]:
import pandas as pd
import numpy as np

df91= pd.read_csv("./final_test_output.csv")
df92= pd.read_csv("./final_test_output2.csv")
df93= pd.read_csv("./final_test_output3.csv")
df94= pd.read_csv("./final_test_output4.csv")
df= pd.concat([df91, df92, df93, df94], axis=0)
print(df.shape)
print(df.info())
df.head()

(131175, 2)
<class 'pandas.core.frame.DataFrame'>
Index: 131175 entries, 0 to 26177
Data columns (total 2 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   index           131175 non-null  int64
 1   ans_entity_val  87941 non-null   object
dtypes: int64(1), object(1)
memory usage: 3.0+ MB
None

   index ans_entity_val
0      0      78.0 inch
1      1        42.0 cm
2      2       200.0 cm
3      3            NaN
4      4            NaN

In [2]:
duplicates = df[df.duplicated(subset=['index'], keep=False)]
duplicates
# df11.head()

Empty DataFrame
Columns: [index, ans_entity_val]
Index: []

In [3]:
print(df['ans_entity_val'].isnull().sum())
df2= df.copy()
df2.head()

43234

   index ans_entity_val
0      0      78.0 inch
1      1        42.0 cm
2      2       200.0 cm
3      3            NaN
4      4            NaN

In [4]:
df2['ans_entity_val']= df2['ans_entity_val'].fillna('Val Unit')
df2[df2['ans_entity_val'].isnull()]

Empty DataFrame
Columns: [index, ans_entity_val]
Index: []

In [5]:
print(len(df2['ans_entity_val'].unique()))
df2['ans_entity_val'].unique()

14334

array(['78.0 inch', '42.0 cm', '200.0 cm', ..., '24.9 ounce',
       '6.0 floz472ml', '8.45 milliliter'], dtype=object)

In [8]:
df2['entity_value'] = df2['ans_entity_val'].apply(
    lambda x: x.strip().split(' ')[0] if isinstance(x, str) and ' ' in x else (x.strip() if isinstance(x, str) else x)
)
df2['entity_unit'] = df2['ans_entity_val'].apply(
    lambda x: x.strip().split(' ')[1] if isinstance(x, str) and len(x.strip().split(' ')) > 1 else None
)

print(df2.shape)
df2.head(20)

(131175, 4)

    index   ans_entity_val entity_value entity_unit
0       0        78.0 inch         78.0        inch
1       1          42.0 cm         42.0          cm
2       2         200.0 cm        200.0          cm
3       3         Val Unit          Val        Unit
4       4         Val Unit          Val        Unit
5       5          90.0 cm         90.0          cm
6       6         10.50 cm        10.50          cm
7       7         1.4 inch          1.4        inch
8       8  40.0 centimetre         40.0  centimetre
9       9  40.0 centimetre         40.0  centimetre
10     10         Val Unit          Val        Unit
11     11  30.6 centimetre         30.6  centimetre
12     12         4.3 inch          4.3        inch
13     13         4.3 inch          4.3        inch
14     14         4.3 inch          4.3        inch
15     15         Val Unit          Val        Unit
16     16         Val Unit          Val        Unit
17     17         Val Unit          Val        Unit
18     18         Val Unit          Val        Unit
19     19       208.0 volt        208.0        volt

In [9]:
df2['entity_unit']= df2['entity_unit'].str.lower()
df2.head(20)

    index   ans_entity_val entity_value entity_unit
0       0        78.0 inch         78.0        inch
1       1          42.0 cm         42.0          cm
2       2         200.0 cm        200.0          cm
3       3         Val Unit          Val        unit
4       4         Val Unit          Val        unit
5       5          90.0 cm         90.0          cm
6       6         10.50 cm        10.50          cm
7       7         1.4 inch          1.4        inch
8       8  40.0 centimetre         40.0  centimetre
9       9  40.0 centimetre         40.0  centimetre
10     10         Val Unit          Val        unit
11     11  30.6 centimetre         30.6  centimetre
12     12         4.3 inch          4.3        inch
13     13         4.3 inch          4.3        inch
14     14         4.3 inch          4.3        inch
15     15         Val Unit          Val        unit
16     16         Val Unit          Val        unit
17     17         Val Unit          Val        unit
18     18         Val Unit          Val        unit
19     19       208.0 volt        208.0        volt

In [10]:
uniqueUnits= df2['entity_unit'].unique()
print(len(uniqueUnits))
print(uniqueUnits)

1111
['inch' 'cm' 'unit' ... 'sas' 'floz(340' 'floz472ml']

In [11]:
entity_unit_map = {
    'width': {'centimetre', 'foot', 'inch', 'metre', 'millimetre', 'yard'},
    'depth': {'centimetre', 'foot', 'inch', 'metre', 'millimetre', 'yard'},
    'height': {'centimetre', 'foot', 'inch', 'metre', 'millimetre', 'yard'},
    'item_weight': {'gram',
        'kilogram',
        'microgram',
        'milligram',
        'ounce',
        'pound',
        'ton'},
    'maximum_weight_recommendation': {'gram',
        'kilogram',
        'microgram',
        'milligram',
        'ounce',
        'pound',
        'ton'},
    'voltage': {'kilovolt', 'millivolt', 'volt'},
    'wattage': {'kilowatt', 'watt'},
    'item_volume': {'centilitre',
        'cubic foot',
        'cubic inch',
        'cup',
        'decilitre',
        'fluid ounce',
        'gallon',
        'imperial gallon',
        'litre',
        'microlitre',
        'millilitre',
        'pint',
        'quart'}
}

allowed_units = {unit for entity in entity_unit_map for unit in entity_unit_map[entity]}
entity_list= []
for entity in allowed_units:
    entity_list.append(entity)

print(len(entity_list))
print(entity_list)

31
['fluid ounce', 'milligram', 'millilitre', 'decilitre', 'inch', 'yard', 'microlitre', 'cup', 'litre', 'cubic inch', 'microgram', 'quart', 'volt', 'watt', 'kilovolt', 'millimetre', 'pint', 'kilowatt', 'cubic foot', 'ton', 'pound', 'ounce', 'gallon', 'centimetre', 'kilogram', 'imperial gallon', 'millivolt', 'centilitre', 'gram', 'metre', 'foot']

In [416]:
entity_list2= ['gram', 'cup', 'milligram', 'kilogram', 'ounce', 'gallon', 'volt', 'watt', 'pound', 'millilitre', 'foot', 'ton', 'decilitre', 'inch', 'litre', 'microgram', 'centimetre', 'quart', 'horsepower', 'kilowatt', 'hour', 'gigabyte', 'millimetre', 'pint', 'centilitre', 'metre', 'carat', 'nits']

# for entity in entity_list2:
#     if entity not in entity_list:
#         entity_list.append(entity)

# for entity in entity_list2:
#     if entity not in entity_list:
#         entity_list.append(entity)

# print(len(entity_list))
# print(entity_list)

In [15]:
goodUnits= entity_list.copy()
badUnits= []

for unit in uniqueUnits:
    if unit not in entity_list:
        badUnits.append(unit)

print(len(goodUnits))
print(goodUnits)

print(len(badUnits))
print(badUnits)

31
['fluid ounce', 'milligram', 'millilitre', 'decilitre', 'inch', 'yard', 'microlitre', 'cup', 'litre', 'cubic inch', 'microgram', 'quart', 'volt', 'watt', 'kilovolt', 'millimetre', 'pint', 'kilowatt', 'cubic foot', 'ton', 'pound', 'ounce', 'gallon', 'centimetre', 'kilogram', 'imperial gallon', 'millivolt', 'centilitre', 'gram', 'metre', 'foot']
1088
['cm', 'unit', None, 'enough', 'millimeter', 'mm', 'floz', 'cm(23.6")', 'steak', '25.7.cm"', 'ltd', '', 'wdusti', '2.83inch', 'diameter', 'centimeter', 'g', 'meter', '3.5"', 'in.', 'determine', 'fluid', 'cm**', '22.2', '3', 'piece', 'newton', 'grams', '2', 'oz', 'inches', '24.0', 'pounds', 'cubic', 'available', 'air', 'applicable', 'airflow', 'in', 'milliliter', 'absorbant', 'bulb', 'youthsize', 'cut', '1.37', 'chicken', '60hz', 'numerical_value', 's6%stronge', '5x7', 'cm",', 'fluid_ounce', '3.14/8,', 'envirocore', '13"', 'gramco', '6.0', 'not', 'whole', '5.0', '13.8', '110cm', 'aey', 'fl0z', '20.5cm', 'ithum', 'found', '15.0', 'r3', 'soce', 'liter', 'numerical', '28.0', 'cm³', 'gigabyte', 'second', 'hd', 'ibs', 'fl.oz.', 'value]', 'potato', 'hints', 'milligrams', 'bar', 'bend', 'pet', 'in/40', '18"', 'ml', 'user', 'net', 'in/4.0', '24%', 'percent', 'fl', 'provided', 'l85', 'color', '[voltage', 'horsepower', 'packets', '17.5', 'preductoffrance', '"', '6cm', 'and', 'cm(35,4")', '23', 'specified', 'gnl', '40', 'compact', 'salad', 'ridgid', '&sour', 'avidpow', 'lb', 'x18', 'ampere', '5', '8.19d', '41.25-47.25', '260cn', '03', 'qt', 'food', 'deli', 'b/m2', 'ml/1fl.oz', 'degree', 'sleep', 'large', 'floz946ml', '100', 'pack', '20.0', 'mutant', 'coffee', 'floz.', '4mm(thickness)', 'mango', '18', 'volts', 'material"', 'lers/simples', 'billion', 'btu', 'gm', 'adult', 'trakitri', '120.0', 'capsule', '48', 'ml/0.60fl.oz.', 'rpm', 'mushroom', 'e41egs', '5cm', 'ounces', 'bounces', 'hor', '195', 'gsm', 'depth', 'wuxga2,000100', '53125', 'in/cm', '.', 'floz(473ml)', 'softchews', 'to', 'double', '45cm', '10.15d', 'brushless', '113g', '1cm', 'tablet', 'kg', '30cm', '{30.0}', 'arty', 'floz330', '40mm', 'provide', 'oz59ml', 'soups&sauces', '150cm/59inch', '9.8', '136mm', 'l', 'potaocrs', 'lyric', 'lbs', 'floz330ml', '2x', 'tile', 'a312/', 'million', 'pixel', 'fast-absorbing', '10.2"', 'oz.', 'hangers', 'cm²', 'data', 'scoops', 'sq', 'btus', '4100', '+', 'speed', '8.1in', '43mm/1.69inch', 'cm40.4', '20cm', 'dollar', 'amp', '322-17', 'dre', 'closed:', 'pcs', 'batteries', 'watts', 'bags', 'design', 'government', 'exos7e8', '1f1908n', 'blade', 'fl.oz', 'style', 'double-sided', 'cans', 'oz/ml', 'ro', '2.0e', '42cm', 'miom', 'carcam', '12.7"', 'capacity"', 'floz33ml', 'unknown', 'epsom', 'rfx0_e', 'cm²",', 'kabab', '200', 'mile', '17.63"', 'cubic_inch', 'grammes', 'millimetres', 'e8.', 'wh', 'calopies', '184', 'made', '162', 'left', 'imported', '7.59d', '55085', 'ca', '20', '0,021', 'n/a', 'resealable', 'unit:', 'pages', 'mg', 'cm/8.26in', '17.5cm', 'special', 'handle', 'in/12.6', 'cm/12in', 'not_applicable', 'cfm/watt', 'drops', '40%', 'calorie', 'sheets', 'luggage', 'home', 'work', 'ac90-265v', 'handheld', 'size', 'floz(355ml', 'oz/', 'feet', 'floating_integer', 'height', 'kilocalories', '20w', 'box', 'gigabytes', 'bag', 'lumens', 'hour', '8cm/3.2"', '210cm', 'cms', 'tl/', 'ok', '24t', 'floz355', 'mah', 'milliampere-hour', 'tmakita', 'determined', 'cm28.0', 'in/49.0', 'o', '161250va0', 'graphics', '13cm/5inch', 'cm3', 'oz(473', '0', '50.0', 'square', 'umens', 'here', 'miles', '-ej', 'led', '&cheese', 'cm24.8', 'floz355ml', '6.7in', 'wisbes', '3.51n', 'er', 'terabyte', 'clarify', 'grey', '3in', 'froppe', '3x3m', 'skil,...', 'btu/h', '5.9,', '7mm', 'ml/1oz', 'calories', '28"', 'then', 'floz/710ml', 'x1', 'coins', '.4cm', '20.7cm/8.1', 'determinable', 'k', '0.1inch', 'pieces', 'me', 'izeeker', 'centimetres', 'lbs/705g', 'android10.0', 'cu.t', 'fat', 'k230v', 'or', 'fiches', '43/16"', '/', 'gb', 'kilograms', '14mm', '220v-5400w25a', 'cm/2.36in', 'cm/inch', 'ft', 'in/28.0cm', 'millimeters', '1181', '127mm', 'filters', 'ir', 'dog', 'smartest', 'teccpo', '**', 'antennas', 'floz(355ml)', 'times', 'm³', '178mm', 'integer', '41"', 'company', 'k-cuppods', '26', 'omato', 'rotation', '29', '0.08a', '4-18-288', '11.0cm', 'from40-120lb', 'hours', 'shcts', 'floz1p1473ml', 'double_thickness', 'singlebrgits', '54', '90mm', '240', 'cm/s²', 'cac', 'resuittast', 'photos', 'ruler', 'light', 'ce', 'meters', 'playstation', '9.5"', 'compatible', 'mm/inch', '-257mm', 'ychika', 'wood', '7.25', 'e375474', 'ib', 'g/m2', 'in/36', '3.7in)', 'makita', 'micromillimeter', 'cfm', 'thousand', '12.76w', '1', '72"', '87cm', 'gps', 'alphasonik', 'packages', '7.5', '22cm/8.6in', 'i', 'cm.', 'base', 'een', '123cm', 'beam', 'cm/4.3in', 'popthe', 'tosttos', 'charge', 'morice', 'serving', '95mm', 'jhofa', '0.7cm/0.27in', '5.1cm', 'veodymiun', '0.8cm/0.3in', 'acrilico', '/1.42".', '4.1"**', ',', 'ml4oz', 'lumen', 'ml/o.60fl.oz.', 'family', 'three', '52mm', 'kcal', 'mic', 'micrometre', '6.3in', 'aa', '29cm', 'r/min', 'cm/in', 'they', '34', 'us', 'cuadro', 'efficiency', '15cm/5.91"', 'a', '36', 'rug', '3x5m', 'cardvr', 'high', '1.8', 'micrometer', 'information', 'energy', 'be', 'in/34', '24mm', 'mph', '6', '55cm', "you'd", 'lnch', 'nanogram', '-ans', 'defined', '29.0', '90.0,', 'no', '20cm/7.87in', '1.3inch', 'cc/ml', 'milliamp', 'milliampere', 'in/36.0cm', '15in', 'gr', 'adhesive', 'iov', 'performancee', 'dia', 'your', 'decimal', 'ralevce', '95', '9.53d', 'f8"4', '2.2inch', 'degrees', '4.0m', '11.9,', 'cm/2.76in', '12cm/4.72in', 'oz60', 'l8s', 'count', 'floz355m', '58.0', 'ram', '1.6]', '2in', '2cm', '5cm/1.97in', 'can', 'oz80g', '200pcs/set', '8cm', 'ml/3.71', 'who', '5in', 'mr.go', '17mm', 'x16.9', 'easy', 'kiss', 'qqty1', 'spin', 'm24', '-off', 'microfarad', 'journeys', '22mm', 'oz(355ml)', 'centimeters', '28cm', '55mm', 'for', 'details', '60x200cm', 'sinocmp', "16'", '(ml)', '20colors', 'silber', 'lozenges', 'sheet', 'complex', '6.5cm', 'uueh', '60.0', 'in/35.0', 'dc10~30v', 'letter', 'max', 'clear', 'xbox', '7', '10"', 'lb/sheet', '2.5x2.5m', 'cauno', 'capacity', '8"', 'trif', '*', '41cm', 'choking', 'mrc', '*please', 'weight', 'green', '16in/', '60cm', 'moooon', '15mm', '3/5', 'quality', '24cm', 'm', 'h', '200cm', '24x19x8cm', 'in/95', 'keto', '100.0', '25.5cm/10in', 'set-up', '13.6cm', 'filter', '7.6', 'cubic_foot', 'milliwatt', 'mm/5.5in', 'cm/3.4in', 'millile', 'nl', 'floz/207ml', 'cubic_meter', '13500', 'fregc', '2.5ft', 'soap', 'cm/4.2', '18/8', '2.2k', '41', 'mooe3-sntry', 'loads', '19mm', 'ml(3.9', 'enjoy', '7in', '4.7', 'ovelmp', 'ml0.25fl.oz', '300w', 'coin', 'with', 'sq.ft', 'line', 'oraa', '-rc', '/unit', 'bars', '7cm', '10x', 'cm/18', 'cm(16.1)', 'pcsd', '?', 'mm3', 'gallons', 'onservadores', 'kilometer', 'sunshine', 'vac', 'cylinder', '(15.88cm)', 'poured', 'save', 'r', 'atx', '&', 'walimex', 'sche', 'helle', '5.19inch', 'hold', 'adaptor', '130cm/', 'nits', '24"', '(114mm)', 'fish', 'candles', 'oz/200ml', '6.30"', 'lightpack20-21', '9.5', 'millilitres', '40"', 'voltage', 'packs', "uno'", 'm3/h', 'strength', 'divider', 'ips', '20"', 'units', '19.7', 'sq.ft.', '5.5in', 'set', '108inch', "k.o.4x's", '31cm', 'truslyour', 'b', 'dc12v', 'cards', '1500pcs85x50cm', '2"', '35mm/1.37in', 'planning', 'n/cm', 'premier', 'fx4', 'proof', '1.7', 'w', 'would', 'degree_fahrenheit', 'mm³', 'plates', 'pulgadas', 'no_unit', '47mm71.85in', 'gold', '60', 'mm/0.55in', 's', '8cm!', 'fan', 'assembly', 'jolly', 'ml/net', '1.7inch', '4.4', 'picture-page', 'year', 'afc', 'ml/8fl', 'yards', '100cm', 'fully', 'the', 'more', 'bench', 'value', 'coral', 'ultra', 'nch', 'hnc', 'b+', 'c', '2.5cm(8pcs)', '2.25x3.5"', 'u.s.qt(1l)', 'piece(s)', '54mm', 'tata', 'in/150', 'pods', 'hack', '1.8"', 'of10-60,so', 'lbtimkenload', 'mm/1.68in', 'mmlt', '120', 'bullet', '7,8', 'vdc', 'usb', '8mm', 'inch",', 'none', '5.7in', 'unit=cup', 'cm/8.66in', '{unit}', '5mm', 'flozcan', '6.5subwoofer44', '4', 'pood', 'gram/square_meter', 'untreated', '0.5"', 'verschiedene', '9.8"', 'day', 'ml/0.5', 'mm/1.46in', 'apulf-ot', '5.8in', '5yyayt', 'strips', 'square-meter', '7.48in', 'bs/100', '30"', 'smaller', 'of', '14mm/0.55in', 'screws', '15cm/5.9in', 'js', '0.21,', 'profcut', 'oz/g', 'headset', '12v-dc', 'carmo', '8ohm/15vc', '115mm', '30ml', 'undefined', 'e2627', '79.52"', '5.7', 'stencil', '227mm', 'oz(77ml)', 'tomas', '8.75', 'ierral', '60in', 'teeth', '9/16"', '38', 'waterproof', 'bushnel', 'i/w', 'display', '91/8"', 'need', 'sketchbook', '8cm/3.15in', "44.9cm/17.7in'", 'mil', 'preclsely', 'rap', '47cm', 'x', 'yoga', '12inch/30cm', '11cm/4.33inch', '13cm/5.1in', 'cm/2.95in', 'uto', 'output5v2a', '15', '(50cm)', 'which', '12*18inch', '10', 'percentage', 'm711', '33"', 'odtio', 'makes', 'ml/5fl', 'fc', 'bottle', 'fl.', '25', 'ml/o.5', 'canvas', '6.35mm', 'tb', '30x', 'plus', '8m', 'fl.oz/15ml', 'mid', 'dome', 'ml/4oz', 'unit=grams', 'junior3-pack', '5oowatt', 'fl.oz(77ml', 'ml/8.5', 'wires', 'days', 'j', 'floz/237ml', 'floz(237', 'bpbaka', 'draw', 'acre', 'tello', 'ml/0.5oz', 'cc', 'ml/1.7', 'new', 'cable', 'ratio', 'pump', 'input', 'context', '00', 'page', 'varies]', '5v', 'unit=kg', 'mr-black', 'ml/8', 'oz/236ml', 'impedance', '000', 'samsung', '36w', 'scroll', 'floz/473', 'ml/oz', 'floz/946ml', 'yellow', '32', '20gbps', 'grams/sheet', 'oz/sq', '100lbs', 'grams/square-meter', 'lite', 'rider', 'grams/m2', 'bracket', 'blst', 'barrel', 'minute', 'bocina', '5w', 'floz/414ml', '08', 'floz(1.89l)', 'bolsas', 'cubic_centimeter', 'r63', 'ml/0.24', 'gal', 'byte', 'ssd', 'function', 'minutes', 'sata', 'ibs.', 'ml/0.51fl.oz.', 'ml/2', 'millifloz', 'ball', '00000', 'floz/10ml', 'ka', 'shock-proof', 'kids', 'aluminum', 'megahertz', 'floz473ml', 'oz/100g', 'solid', 'ib/400g', 'floz1qt546m', 'dc+3.3v0.6a', 'ibsd', 'psi/bar', 'g/lbs', 'cnc', '1/16-3/4', 'oz1l', 'protective', 'almond', 'medium', 'floz/29ml', '3a', 'floz/400', '2-fluid', 'safe', 'pounds@7psi', 'snowballs', 'oz59', 'floz/240ml', 'power', 'as', 'ml/1floz', 'mb', '30.0', 'melt"', 'schrader', 'ml/8fl.oz.', 'grams/square', 'gigabit', 'floz(325ml)', 'servings', 'jvc', 'oz(20ml)', 'powersupply', 'floz/86mle', 'madefor', 'blue', '186ml', 'built', '13.4', 'syrup', '0.16', 'ml/3.89', 'eternal', 'ml/2fl', 'oc', 'ml/0.67', 'floz(414', 'bls', 'concentrated', 'state', 'hy', 'ml/0.50', 'csm', 'ml(4oz)', 'optical', 'floz(1pt)473ml', 'horntweeter', 'fl.oz/473ml', 'cssa', '900gb', 'oz(355', 'bottles', 'cu/m', 'fl.oz6ml', 'half', 'oz/8.5', 'psi', 'ml/1fl', 'ultra-powerful', 'sml', 'floz/6m', 'floz/400ml', 'woofer', 'oz/300ml', 'floz/473ml', 'leave-in', 'oz/100gr', 'oz/100', 'car', 'oz355ml', 'load', 'length', 'ml/1fl.oz.', 'level', 'ml/0.35', 'floz(340ml)', 'z', 'ozhalf', 'ozhal', 'hog', 'ml/1.01', 'floz35ml', 'skin.', '72.8-gb', 'digital', 'x4', '14', '8-inch', 'lozenge', 'tool', 'collapsed', 'cerohs', 'ib/g', 'aquarium', 'us_quart', 'possible', 'oz/10ml', 'floz710n', 'liters', 'floz1qt/946ml', 'together', 'seed', '56', '12', 'yds/215m', 'grain', 'sas', 'floz(340', 'floz472ml']

In [418]:
# df50= df2[df2['entity_unit'].isin(goodUnits)]
# print(df50.shape)
# df50.head()

In [16]:
df2.shape

(131175, 4)

In [17]:
unit_map = {
    'millimetre': ['mm', 'millimeter', 'millimetres', 'millimeters'],
    'milligram': ['mg', 'milligrams'],
    'kilowatt': ['kW', 'kilowatts'],
    'gallon': ['gal', 'gallons'],
    'cubic foot': ['ft³', 'cubic feet'],
    'microlitre': ['µL', 'microliter', 'microlitres', 'microliters'],
    'imperial gallon': ['imp gal', 'imperial gallons'],
    'centilitre': ['cL', 'centiliter', 'centilitres', 'centiliters'],
    'millilitre': ['mL', 'milliliter', 'millilitres', 'milliliters'],
    'ounce': ['oz', 'ounces'],
    'litre': ['L', 'liter', 'litres', 'liters'],
    'microgram': ['µg', 'micrograms'],
    'kilovolt': ['kV', 'kilovolts'],
    'watt': ['W', 'watts'],
    'millivolt': ['mV', 'millivolts'],
    'centimetre': ['cm', 'centimeter', 'centimetres', 'centimeters'],
    'ton': ['t', 'tons'],
    'foot': ['ft', 'feet'],
    'fluid ounce': ['fl oz', 'fluid ounces'],
    'volt': ['V', 'volts'],
    'decilitre': ['dL', 'deciliter', 'decilitres', 'deciliters'],
    'pint': ['pt', 'pints'],
    'quart': ['qt', 'quarts'],
    'inch': ['in', 'inches'],
    'metre': ['m', 'meter', 'metres', 'meters'],
    'yard': ['yd', 'yards'],
    'cubic inch': ['in³', 'cubic inches'],
    'pound': ['lb', 'pounds'],
    'cup': ['cup', 'cups'],
    'kilogram': ['kg', 'kilograms'],
    'gram': ['g', 'grams']
}
print(len(unit_map))

dfBadUnitsMap= {}

31

In [22]:
for unit in badUnits:
    # print(unit)
    for key, value in unit_map.items():
        if unit in value:
            dfBadUnitsMap[unit]= key
            if unit in badUnits:
                badUnits.remove(unit)
            
print(len(dfBadUnitsMap))
print(dfBadUnitsMap)
print(len(badUnits))
print(badUnits)

35
{'cm': 'centimetre', 'millimeter': 'millimetre', 'centimeter': 'centimetre', 'meter': 'metre', 'grams': 'gram', 'oz': 'ounce', 'pounds': 'pound', 'in': 'inch', 'liter': 'litre', 'milligrams': 'milligram', 'lb': 'pound', 'qt': 'quart', 'volts': 'volt', 'ounces': 'ounce', 'kg': 'kilogram', 'watts': 'watt', 'millimetres': 'millimetre', 'mg': 'milligram', 'feet': 'foot', 'centimetres': 'centimetre', 'kilograms': 'kilogram', 'ft': 'foot', 'millimeters': 'millimetre', 'meters': 'metre', 'centimeters': 'centimetre', 'm': 'metre', 'gallons': 'gallon', 'millilitres': 'millilitre', 'yards': 'yard', 'gal': 'gallon', 'liters': 'litre', 'mm': 'millimetre', 'g': 'gram', 'inches': 'inch', 'milliliter': 'millilitre'}
1053
['unit', None, 'enough', 'floz', 'cm(23.6")', 'steak', '25.7.cm"', 'ltd', '', 'wdusti', '2.83inch', 'diameter', '3.5"', 'in.', 'determine', 'fluid', 'cm**', '22.2', '3', 'piece', 'newton', '2', '24.0', 'cubic', 'available', 'air', 'applicable', 'airflow', 'absorbant', 'bulb', 'youthsize', 'cut', '1.37', 'chicken', '60hz', 'numerical_value', 's6%stronge', '5x7', 'cm",', 'fluid_ounce', '3.14/8,', 'envirocore', '13"', 'gramco', '6.0', 'not', 'whole', '5.0', '13.8', '110cm', 'aey', 'fl0z', '20.5cm', 'ithum', 'found', '15.0', 'r3', 'soce', 'numerical', '28.0', 'cm³', 'gigabyte', 'second', 'hd', 'ibs', 'fl.oz.', 'value]', 'potato', 'hints', 'bar', 'bend', 'pet', 'in/40', '18"', 'ml', 'user', 'net', 'in/4.0', '24%', 'percent', 'fl', 'provided', 'l85', 'color', '[voltage', 'horsepower', 'packets', '17.5', 'preductoffrance', '"', '6cm', 'and', 'cm(35,4")', '23', 'specified', 'gnl', '40', 'compact', 'salad', 'ridgid', '&sour', 'avidpow', 'x18', 'ampere', '5', '8.19d', '41.25-47.25', '260cn', '03', 'food', 'deli', 'b/m2', 'ml/1fl.oz', 'degree', 'sleep', 'large', 'floz946ml', '100', 'pack', '20.0', 'mutant', 'coffee', 'floz.', '4mm(thickness)', 'mango', '18', 'material"', 'lers/simples', 'billion', 'btu', 'gm', 'adult', 'trakitri', '120.0', 'capsule', '48', 'ml/0.60fl.oz.', 'rpm', 'mushroom', 'e41egs', '5cm', 'bounces', 'hor', '195', 'gsm', 'depth', 'wuxga2,000100', '53125', 'in/cm', '.', 'floz(473ml)', 'softchews', 'to', 'double', '45cm', '10.15d', 'brushless', '113g', '1cm', 'tablet', '30cm', '{30.0}', 'arty', 'floz330', '40mm', 'provide', 'oz59ml', 'soups&sauces', '150cm/59inch', '9.8', '136mm', 'l', 'potaocrs', 'lyric', 'lbs', 'floz330ml', '2x', 'tile', 'a312/', 'million', 'pixel', 'fast-absorbing', '10.2"', 'oz.', 'hangers', 'cm²', 'data', 'scoops', 'sq', 'btus', '4100', '+', 'speed', '8.1in', '43mm/1.69inch', 'cm40.4', '20cm', 'dollar', 'amp', '322-17', 'dre', 'closed:', 'pcs', 'batteries', 'bags', 'design', 'government', 'exos7e8', '1f1908n', 'blade', 'fl.oz', 'style', 'double-sided', 'cans', 'oz/ml', 'ro', '2.0e', '42cm', 'miom', 'carcam', '12.7"', 'capacity"', 'floz33ml', 'unknown', 'epsom', 'rfx0_e', 'cm²",', 'kabab', '200', 'mile', '17.63"', 'cubic_inch', 'grammes', 'e8.', 'wh', 'calopies', '184', 'made', '162', 'left', 'imported', '7.59d', '55085', 'ca', '20', '0,021', 'n/a', 'resealable', 'unit:', 'pages', 'cm/8.26in', '17.5cm', 'special', 'handle', 'in/12.6', 'cm/12in', 'not_applicable', 'cfm/watt', 'drops', '40%', 'calorie', 'sheets', 'luggage', 'home', 'work', 'ac90-265v', 'handheld', 'size', 'floz(355ml', 'oz/', 'floating_integer', 'height', 'kilocalories', '20w', 'box', 'gigabytes', 'bag', 'lumens', 'hour', '8cm/3.2"', '210cm', 'cms', 'tl/', 'ok', '24t', 'floz355', 'mah', 'milliampere-hour', 'tmakita', 'determined', 'cm28.0', 'in/49.0', 'o', '161250va0', 'graphics', '13cm/5inch', 'cm3', 'oz(473', '0', '50.0', 'square', 'umens', 'here', 'miles', '-ej', 'led', '&cheese', 'cm24.8', 'floz355ml', '6.7in', 'wisbes', '3.51n', 'er', 'terabyte', 'clarify', 'grey', '3in', 'froppe', '3x3m', 'skil,...', 'btu/h', '5.9,', '7mm', 'ml/1oz', 'calories', '28"', 'then', 'floz/710ml', 'x1', 'coins', '.4cm', '20.7cm/8.1', 'determinable', 'k', '0.1inch', 'pieces', 'me', 'izeeker', 'lbs/705g', 'android10.0', 'cu.t', 'fat', 'k230v', 'or', 'fiches', '43/16"', '/', 'gb', '14mm', '220v-5400w25a', 'cm/2.36in', 'cm/inch', 'in/28.0cm', '1181', '127mm', 'filters', 'ir', 'dog', 'smartest', 'teccpo', '**', 'antennas', 'floz(355ml)', 'times', 'm³', '178mm', 'integer', '41"', 'company', 'k-cuppods', '26', 'omato', 'rotation', '29', '0.08a', '4-18-288', '11.0cm', 'from40-120lb', 'hours', 'shcts', 'floz1p1473ml', 'double_thickness', 'singlebrgits', '54', '90mm', '240', 'cm/s²', 'cac', 'resuittast', 'photos', 'ruler', 'light', 'ce', 'playstation', '9.5"', 'compatible', 'mm/inch', '-257mm', 'ychika', 'wood', '7.25', 'e375474', 'ib', 'g/m2', 'in/36', '3.7in)', 'makita', 'micromillimeter', 'cfm', 'thousand', '12.76w', '1', '72"', '87cm', 'gps', 'alphasonik', 'packages', '7.5', '22cm/8.6in', 'i', 'cm.', 'base', 'een', '123cm', 'beam', 'cm/4.3in', 'popthe', 'tosttos', 'charge', 'morice', 'serving', '95mm', 'jhofa', '0.7cm/0.27in', '5.1cm', 'veodymiun', '0.8cm/0.3in', 'acrilico', '/1.42".', '4.1"**', ',', 'ml4oz', 'lumen', 'ml/o.60fl.oz.', 'family', 'three', '52mm', 'kcal', 'mic', 'micrometre', '6.3in', 'aa', '29cm', 'r/min', 'cm/in', 'they', '34', 'us', 'cuadro', 'efficiency', '15cm/5.91"', 'a', '36', 'rug', '3x5m', 'cardvr', 'high', '1.8', 'micrometer', 'information', 'energy', 'be', 'in/34', '24mm', 'mph', '6', '55cm', "you'd", 'lnch', 'nanogram', '-ans', 'defined', '29.0', '90.0,', 'no', '20cm/7.87in', '1.3inch', 'cc/ml', 'milliamp', 'milliampere', 'in/36.0cm', '15in', 'gr', 'adhesive', 'iov', 'performancee', 'dia', 'your', 'decimal', 'ralevce', '95', '9.53d', 'f8"4', '2.2inch', 'degrees', '4.0m', '11.9,', 'cm/2.76in', '12cm/4.72in', 'oz60', 'l8s', 'count', 'floz355m', '58.0', 'ram', '1.6]', '2in', '2cm', '5cm/1.97in', 'can', 'oz80g', '200pcs/set', '8cm', 'ml/3.71', 'who', '5in', 'mr.go', '17mm', 'x16.9', 'easy', 'kiss', 'qqty1', 'spin', 'm24', '-off', 'microfarad', 'journeys', '22mm', 'oz(355ml)', '28cm', '55mm', 'for', 'details', '60x200cm', 'sinocmp', "16'", '(ml)', '20colors', 'silber', 'lozenges', 'sheet', 'complex', '6.5cm', 'uueh', '60.0', 'in/35.0', 'dc10~30v', 'letter', 'max', 'clear', 'xbox', '7', '10"', 'lb/sheet', '2.5x2.5m', 'cauno', 'capacity', '8"', 'trif', '*', '41cm', 'choking', 'mrc', '*please', 'weight', 'green', '16in/', '60cm', 'moooon', '15mm', '3/5', 'quality', '24cm', 'h', '200cm', '24x19x8cm', 'in/95', 'keto', '100.0', '25.5cm/10in', 'set-up', '13.6cm', 'filter', '7.6', 'cubic_foot', 'milliwatt', 'mm/5.5in', 'cm/3.4in', 'millile', 'nl', 'floz/207ml', 'cubic_meter', '13500', 'fregc', '2.5ft', 'soap', 'cm/4.2', '18/8', '2.2k', '41', 'mooe3-sntry', 'loads', '19mm', 'ml(3.9', 'enjoy', '7in', '4.7', 'ovelmp', 'ml0.25fl.oz', '300w', 'coin', 'with', 'sq.ft', 'line', 'oraa', '-rc', '/unit', 'bars', '7cm', '10x', 'cm/18', 'cm(16.1)', 'pcsd', '?', 'mm3', 'onservadores', 'kilometer', 'sunshine', 'vac', 'cylinder', '(15.88cm)', 'poured', 'save', 'r', 'atx', '&', 'walimex', 'sche', 'helle', '5.19inch', 'hold', 'adaptor', '130cm/', 'nits', '24"', '(114mm)', 'fish', 'candles', 'oz/200ml', '6.30"', 'lightpack20-21', '9.5', '40"', 'voltage', 'packs', "uno'", 'm3/h', 'strength', 'divider', 'ips', '20"', 'units', '19.7', 'sq.ft.', '5.5in', 'set', '108inch', "k.o.4x's", '31cm', 'truslyour', 'b', 'dc12v', 'cards', '1500pcs85x50cm', '2"', '35mm/1.37in', 'planning', 'n/cm', 'premier', 'fx4', 'proof', '1.7', 'w', 'would', 'degree_fahrenheit', 'mm³', 'plates', 'pulgadas', 'no_unit', '47mm71.85in', 'gold', '60', 'mm/0.55in', 's', '8cm!', 'fan', 'assembly', 'jolly', 'ml/net', '1.7inch', '4.4', 'picture-page', 'year', 'afc', 'ml/8fl', '100cm', 'fully', 'the', 'more', 'bench', 'value', 'coral', 'ultra', 'nch', 'hnc', 'b+', 'c', '2.5cm(8pcs)', '2.25x3.5"', 'u.s.qt(1l)', 'piece(s)', '54mm', 'tata', 'in/150', 'pods', 'hack', '1.8"', 'of10-60,so', 'lbtimkenload', 'mm/1.68in', 'mmlt', '120', 'bullet', '7,8', 'vdc', 'usb', '8mm', 'inch",', 'none', '5.7in', 'unit=cup', 'cm/8.66in', '{unit}', '5mm', 'flozcan', '6.5subwoofer44', '4', 'pood', 'gram/square_meter', 'untreated', '0.5"', 'verschiedene', '9.8"', 'day', 'ml/0.5', 'mm/1.46in', 'apulf-ot', '5.8in', '5yyayt', 'strips', 'square-meter', '7.48in', 'bs/100', '30"', 'smaller', 'of', '14mm/0.55in', 'screws', '15cm/5.9in', 'js', '0.21,', 'profcut', 'oz/g', 'headset', '12v-dc', 'carmo', '8ohm/15vc', '115mm', '30ml', 'undefined', 'e2627', '79.52"', '5.7', 'stencil', '227mm', 'oz(77ml)', 'tomas', '8.75', 'ierral', '60in', 'teeth', '9/16"', '38', 'waterproof', 'bushnel', 'i/w', 'display', '91/8"', 'need', 'sketchbook', '8cm/3.15in', "44.9cm/17.7in'", 'mil', 'preclsely', 'rap', '47cm', 'x', 'yoga', '12inch/30cm', '11cm/4.33inch', '13cm/5.1in', 'cm/2.95in', 'uto', 'output5v2a', '15', '(50cm)', 'which', '12*18inch', '10', 'percentage', 'm711', '33"', 'odtio', 'makes', 'ml/5fl', 'fc', 'bottle', 'fl.', '25', 'ml/o.5', 'canvas', '6.35mm', 'tb', '30x', 'plus', '8m', 'fl.oz/15ml', 'mid', 'dome', 'ml/4oz', 'unit=grams', 'junior3-pack', '5oowatt', 'fl.oz(77ml', 'ml/8.5', 'wires', 'days', 'j', 'floz/237ml', 'floz(237', 'bpbaka', 'draw', 'acre', 'tello', 'ml/0.5oz', 'cc', 'ml/1.7', 'new', 'cable', 'ratio', 'pump', 'input', 'context', '00', 'page', 'varies]', '5v', 'unit=kg', 'mr-black', 'ml/8', 'oz/236ml', 'impedance', '000', 'samsung', '36w', 'scroll', 'floz/473', 'ml/oz', 'floz/946ml', 'yellow', '32', '20gbps', 'grams/sheet', 'oz/sq', '100lbs', 'grams/square-meter', 'lite', 'rider', 'grams/m2', 'bracket', 'blst', 'barrel', 'minute', 'bocina', '5w', 'floz/414ml', '08', 'floz(1.89l)', 'bolsas', 'cubic_centimeter', 'r63', 'ml/0.24', 'byte', 'ssd', 'function', 'minutes', 'sata', 'ibs.', 'ml/0.51fl.oz.', 'ml/2', 'millifloz', 'ball', '00000', 'floz/10ml', 'ka', 'shock-proof', 'kids', 'aluminum', 'megahertz', 'floz473ml', 'oz/100g', 'solid', 'ib/400g', 'floz1qt546m', 'dc+3.3v0.6a', 'ibsd', 'psi/bar', 'g/lbs', 'cnc', '1/16-3/4', 'oz1l', 'protective', 'almond', 'medium', 'floz/29ml', '3a', 'floz/400', '2-fluid', 'safe', 'pounds@7psi', 'snowballs', 'oz59', 'floz/240ml', 'power', 'as', 'ml/1floz', 'mb', '30.0', 'melt"', 'schrader', 'ml/8fl.oz.', 'grams/square', 'gigabit', 'floz(325ml)', 'servings', 'jvc', 'oz(20ml)', 'powersupply', 'floz/86mle', 'madefor', 'blue', '186ml', 'built', '13.4', 'syrup', '0.16', 'ml/3.89', 'eternal', 'ml/2fl', 'oc', 'ml/0.67', 'floz(414', 'bls', 'concentrated', 'state', 'hy', 'ml/0.50', 'csm', 'ml(4oz)', 'optical', 'floz(1pt)473ml', 'horntweeter', 'fl.oz/473ml', 'cssa', '900gb', 'oz(355', 'bottles', 'cu/m', 'fl.oz6ml', 'half', 'oz/8.5', 'psi', 'ml/1fl', 'ultra-powerful', 'sml', 'floz/6m', 'floz/400ml', 'woofer', 'oz/300ml', 'floz/473ml', 'leave-in', 'oz/100gr', 'oz/100', 'car', 'oz355ml', 'load', 'length', 'ml/1fl.oz.', 'level', 'ml/0.35', 'floz(340ml)', 'z', 'ozhalf', 'ozhal', 'hog', 'ml/1.01', 'floz35ml', 'skin.', '72.8-gb', 'digital', 'x4', '14', '8-inch', 'lozenge', 'tool', 'collapsed', 'cerohs', 'ib/g', 'aquarium', 'us_quart', 'possible', 'oz/10ml', 'floz710n', 'floz1qt/946ml', 'together', 'seed', '56', '12', 'yds/215m', 'grain', 'sas', 'floz(340', 'floz472ml']

In [23]:
# # Get unique values
# unique_values = set(dfBadUnitsMap.values())

# for v in unique_values:
#     if v not in goodUnits:
#         print(v)

# # Count unique values
# count_unique = len(unique_values)
# print(count_unique)

In [24]:
# df49= df2.copy()

# for key, value in dfBadUnitsMap.items():
#     df49['entity_unit']= df49['entity_unit'].replace(r'\b{}\b'.format(key), value, regex=True)

# df48= df49[df49['entity_unit'].isin(goodUnits)]
# print(df48.shape)
# df48.head()

# df49= df2.copy()



# Step 1: Replace values in 'entity_unit' column using dfBadUnitsMap
for key, value in dfBadUnitsMap.items():
    df2['entity_unit'] = df2['entity_unit'].replace(r'\b{}\b'.format(key), value, regex=True)

# # Step 2: Filter the DataFrame to include only rows where 'entity_unit' is in goodUnits
# df3 = df2[df2['entity_unit'].isin(goodUnits)]
# print(df3.shape)

print(df2.shape)

(131175, 4)

In [27]:
df2.head(20)
print(len(df2['entity_unit'].unique()))
print()

1074

In [33]:
print(badUnits)
badUnits.remove(None)
print(badUnits)

['unit', 'enough', 'floz', 'cm(23.6")', 'steak', '25.7.cm"', 'ltd', '', 'wdusti', '2.83inch', 'diameter', '3.5"', 'in.', 'determine', 'fluid', 'cm**', '22.2', '3', 'piece', 'newton', '2', '24.0', 'cubic', 'available', 'air', 'applicable', 'airflow', 'absorbant', 'bulb', 'youthsize', 'cut', '1.37', 'chicken', '60hz', 'numerical_value', 's6%stronge', '5x7', 'cm",', 'fluid_ounce', '3.14/8,', 'envirocore', '13"', 'gramco', '6.0', 'not', 'whole', '5.0', '13.8', '110cm', 'aey', 'fl0z', '20.5cm', 'ithum', 'found', '15.0', 'r3', 'soce', 'numerical', '28.0', 'cm³', 'gigabyte', 'second', 'hd', 'ibs', 'fl.oz.', 'value]', 'potato', 'hints', 'bar', 'bend', 'pet', 'in/40', '18"', 'ml', 'user', 'net', 'in/4.0', '24%', 'percent', 'fl', 'provided', 'l85', 'color', '[voltage', 'horsepower', 'packets', '17.5', 'preductoffrance', '"', '6cm', 'and', 'cm(35,4")', '23', 'specified', 'gnl', '40', 'compact', 'salad', 'ridgid', '&sour', 'avidpow', 'x18', 'ampere', '5', '8.19d', '41.25-47.25', '260cn', '03', 'food', 'deli', 'b/m2', 'ml/1fl.oz', 'degree', 'sleep', 'large', 'floz946ml', '100', 'pack', '20.0', 'mutant', 'coffee', 'floz.', '4mm(thickness)', 'mango', '18', 'material"', 'lers/simples', 'billion', 'btu', 'gm', 'adult', 'trakitri', '120.0', 'capsule', '48', 'ml/0.60fl.oz.', 'rpm', 'mushroom', 'e41egs', '5cm', 'bounces', 'hor', '195', 'gsm', 'depth', 'wuxga2,000100', '53125', 'in/cm', '.', 'floz(473ml)', 'softchews', 'to', 'double', '45cm', '10.15d', 'brushless', '113g', '1cm', 'tablet', '30cm', '{30.0}', 'arty', 'floz330', '40mm', 'provide', 'oz59ml', 'soups&sauces', '150cm/59inch', '9.8', '136mm', 'l', 'potaocrs', 'lyric', 'lbs', 'floz330ml', '2x', 'tile', 'a312/', 'million', 'pixel', 'fast-absorbing', '10.2"', 'oz.', 'hangers', 'cm²', 'data', 'scoops', 'sq', 'btus', '4100', '+', 'speed', '8.1in', '43mm/1.69inch', 'cm40.4', '20cm', 'dollar', 'amp', '322-17', 'dre', 'closed:', 'pcs', 'batteries', 'bags', 'design', 'government', 'exos7e8', '1f1908n', 'blade', 'fl.oz', 'style', 'double-sided', 'cans', 'oz/ml', 'ro', '2.0e', '42cm', 'miom', 'carcam', '12.7"', 'capacity"', 'floz33ml', 'unknown', 'epsom', 'rfx0_e', 'cm²",', 'kabab', '200', 'mile', '17.63"', 'cubic_inch', 'grammes', 'e8.', 'wh', 'calopies', '184', 'made', '162', 'left', 'imported', '7.59d', '55085', 'ca', '20', '0,021', 'n/a', 'resealable', 'unit:', 'pages', 'cm/8.26in', '17.5cm', 'special', 'handle', 'in/12.6', 'cm/12in', 'not_applicable', 'cfm/watt', 'drops', '40%', 'calorie', 'sheets', 'luggage', 'home', 'work', 'ac90-265v', 'handheld', 'size', 'floz(355ml', 'oz/', 'floating_integer', 'height', 'kilocalories', '20w', 'box', 'gigabytes', 'bag', 'lumens', 'hour', '8cm/3.2"', '210cm', 'cms', 'tl/', 'ok', '24t', 'floz355', 'mah', 'milliampere-hour', 'tmakita', 'determined', 'cm28.0', 'in/49.0', 'o', '161250va0', 'graphics', '13cm/5inch', 'cm3', 'oz(473', '0', '50.0', 'square', 'umens', 'here', 'miles', '-ej', 'led', '&cheese', 'cm24.8', 'floz355ml', '6.7in', 'wisbes', '3.51n', 'er', 'terabyte', 'clarify', 'grey', '3in', 'froppe', '3x3m', 'skil,...', 'btu/h', '5.9,', '7mm', 'ml/1oz', 'calories', '28"', 'then', 'floz/710ml', 'x1', 'coins', '.4cm', '20.7cm/8.1', 'determinable', 'k', '0.1inch', 'pieces', 'me', 'izeeker', 'lbs/705g', 'android10.0', 'cu.t', 'fat', 'k230v', 'or', 'fiches', '43/16"', '/', 'gb', '14mm', '220v-5400w25a', 'cm/2.36in', 'cm/inch', 'in/28.0cm', '1181', '127mm', 'filters', 'ir', 'dog', 'smartest', 'teccpo', '**', 'antennas', 'floz(355ml)', 'times', 'm³', '178mm', 'integer', '41"', 'company', 'k-cuppods', '26', 'omato', 'rotation', '29', '0.08a', '4-18-288', '11.0cm', 'from40-120lb', 'hours', 'shcts', 'floz1p1473ml', 'double_thickness', 'singlebrgits', '54', '90mm', '240', 'cm/s²', 'cac', 'resuittast', 'photos', 'ruler', 'light', 'ce', 'playstation', '9.5"', 'compatible', 'mm/inch', '-257mm', 'ychika', 'wood', '7.25', 'e375474', 'ib', 'g/m2', 'in/36', '3.7in)', 'makita', 'micromillimeter', 'cfm', 'thousand', '12.76w', '1', '72"', '87cm', 'gps', 'alphasonik', 'packages', '7.5', '22cm/8.6in', 'i', 'cm.', 'base', 'een', '123cm', 'beam', 'cm/4.3in', 'popthe', 'tosttos', 'charge', 'morice', 'serving', '95mm', 'jhofa', '0.7cm/0.27in', '5.1cm', 'veodymiun', '0.8cm/0.3in', 'acrilico', '/1.42".', '4.1"**', ',', 'ml4oz', 'lumen', 'ml/o.60fl.oz.', 'family', 'three', '52mm', 'kcal', 'mic', 'micrometre', '6.3in', 'aa', '29cm', 'r/min', 'cm/in', 'they', '34', 'us', 'cuadro', 'efficiency', '15cm/5.91"', 'a', '36', 'rug', '3x5m', 'cardvr', 'high', '1.8', 'micrometer', 'information', 'energy', 'be', 'in/34', '24mm', 'mph', '6', '55cm', "you'd", 'lnch', 'nanogram', '-ans', 'defined', '29.0', '90.0,', 'no', '20cm/7.87in', '1.3inch', 'cc/ml', 'milliamp', 'milliampere', 'in/36.0cm', '15in', 'gr', 'adhesive', 'iov', 'performancee', 'dia', 'your', 'decimal', 'ralevce', '95', '9.53d', 'f8"4', '2.2inch', 'degrees', '4.0m', '11.9,', 'cm/2.76in', '12cm/4.72in', 'oz60', 'l8s', 'count', 'floz355m', '58.0', 'ram', '1.6]', '2in', '2cm', '5cm/1.97in', 'can', 'oz80g', '200pcs/set', '8cm', 'ml/3.71', 'who', '5in', 'mr.go', '17mm', 'x16.9', 'easy', 'kiss', 'qqty1', 'spin', 'm24', '-off', 'microfarad', 'journeys', '22mm', 'oz(355ml)', '28cm', '55mm', 'for', 'details', '60x200cm', 'sinocmp', "16'", '(ml)', '20colors', 'silber', 'lozenges', 'sheet', 'complex', '6.5cm', 'uueh', '60.0', 'in/35.0', 'dc10~30v', 'letter', 'max', 'clear', 'xbox', '7', '10"', 'lb/sheet', '2.5x2.5m', 'cauno', 'capacity', '8"', 'trif', '*', '41cm', 'choking', 'mrc', '*please', 'weight', 'green', '16in/', '60cm', 'moooon', '15mm', '3/5', 'quality', '24cm', 'h', '200cm', '24x19x8cm', 'in/95', 'keto', '100.0', '25.5cm/10in', 'set-up', '13.6cm', 'filter', '7.6', 'cubic_foot', 'milliwatt', 'mm/5.5in', 'cm/3.4in', 'millile', 'nl', 'floz/207ml', 'cubic_meter', '13500', 'fregc', '2.5ft', 'soap', 'cm/4.2', '18/8', '2.2k', '41', 'mooe3-sntry', 'loads', '19mm', 'ml(3.9', 'enjoy', '7in', '4.7', 'ovelmp', 'ml0.25fl.oz', '300w', 'coin', 'with', 'sq.ft', 'line', 'oraa', '-rc', '/unit', 'bars', '7cm', '10x', 'cm/18', 'cm(16.1)', 'pcsd', '?', 'mm3', 'onservadores', 'kilometer', 'sunshine', 'vac', 'cylinder', '(15.88cm)', 'poured', 'save', 'r', 'atx', '&', 'walimex', 'sche', 'helle', '5.19inch', 'hold', 'adaptor', '130cm/', 'nits', '24"', '(114mm)', 'fish', 'candles', 'oz/200ml', '6.30"', 'lightpack20-21', '9.5', '40"', 'voltage', 'packs', "uno'", 'm3/h', 'strength', 'divider', 'ips', '20"', 'units', '19.7', 'sq.ft.', '5.5in', 'set', '108inch', "k.o.4x's", '31cm', 'truslyour', 'b', 'dc12v', 'cards', '1500pcs85x50cm', '2"', '35mm/1.37in', 'planning', 'n/cm', 'premier', 'fx4', 'proof', '1.7', 'w', 'would', 'degree_fahrenheit', 'mm³', 'plates', 'pulgadas', 'no_unit', '47mm71.85in', 'gold', '60', 'mm/0.55in', 's', '8cm!', 'fan', 'assembly', 'jolly', 'ml/net', '1.7inch', '4.4', 'picture-page', 'year', 'afc', 'ml/8fl', '100cm', 'fully', 'the', 'more', 'bench', 'value', 'coral', 'ultra', 'nch', 'hnc', 'b+', 'c', '2.5cm(8pcs)', '2.25x3.5"', 'u.s.qt(1l)', 'piece(s)', '54mm', 'tata', 'in/150', 'pods', 'hack', '1.8"', 'of10-60,so', 'lbtimkenload', 'mm/1.68in', 'mmlt', '120', 'bullet', '7,8', 'vdc', 'usb', '8mm', 'inch",', 'none', '5.7in', 'unit=cup', 'cm/8.66in', '{unit}', '5mm', 'flozcan', '6.5subwoofer44', '4', 'pood', 'gram/square_meter', 'untreated', '0.5"', 'verschiedene', '9.8"', 'day', 'ml/0.5', 'mm/1.46in', 'apulf-ot', '5.8in', '5yyayt', 'strips', 'square-meter', '7.48in', 'bs/100', '30"', 'smaller', 'of', '14mm/0.55in', 'screws', '15cm/5.9in', 'js', '0.21,', 'profcut', 'oz/g', 'headset', '12v-dc', 'carmo', '8ohm/15vc', '115mm', '30ml', 'undefined', 'e2627', '79.52"', '5.7', 'stencil', '227mm', 'oz(77ml)', 'tomas', '8.75', 'ierral', '60in', 'teeth', '9/16"', '38', 'waterproof', 'bushnel', 'i/w', 'display', '91/8"', 'need', 'sketchbook', '8cm/3.15in', "44.9cm/17.7in'", 'mil', 'preclsely', 'rap', '47cm', 'x', 'yoga', '12inch/30cm', '11cm/4.33inch', '13cm/5.1in', 'cm/2.95in', 'uto', 'output5v2a', '15', '(50cm)', 'which', '12*18inch', '10', 'percentage', 'm711', '33"', 'odtio', 'makes', 'ml/5fl', 'fc', 'bottle', 'fl.', '25', 'ml/o.5', 'canvas', '6.35mm', 'tb', '30x', 'plus', '8m', 'fl.oz/15ml', 'mid', 'dome', 'ml/4oz', 'unit=grams', 'junior3-pack', '5oowatt', 'fl.oz(77ml', 'ml/8.5', 'wires', 'days', 'j', 'floz/237ml', 'floz(237', 'bpbaka', 'draw', 'acre', 'tello', 'ml/0.5oz', 'cc', 'ml/1.7', 'new', 'cable', 'ratio', 'pump', 'input', 'context', '00', 'page', 'varies]', '5v', 'unit=kg', 'mr-black', 'ml/8', 'oz/236ml', 'impedance', '000', 'samsung', '36w', 'scroll', 'floz/473', 'ml/oz', 'floz/946ml', 'yellow', '32', '20gbps', 'grams/sheet', 'oz/sq', '100lbs', 'grams/square-meter', 'lite', 'rider', 'grams/m2', 'bracket', 'blst', 'barrel', 'minute', 'bocina', '5w', 'floz/414ml', '08', 'floz(1.89l)', 'bolsas', 'cubic_centimeter', 'r63', 'ml/0.24', 'byte', 'ssd', 'function', 'minutes', 'sata', 'ibs.', 'ml/0.51fl.oz.', 'ml/2', 'millifloz', 'ball', '00000', 'floz/10ml', 'ka', 'shock-proof', 'kids', 'aluminum', 'megahertz', 'floz473ml', 'oz/100g', 'solid', 'ib/400g', 'floz1qt546m', 'dc+3.3v0.6a', 'ibsd', 'psi/bar', 'g/lbs', 'cnc', '1/16-3/4', 'oz1l', 'protective', 'almond', 'medium', 'floz/29ml', '3a', 'floz/400', '2-fluid', 'safe', 'pounds@7psi', 'snowballs', 'oz59', 'floz/240ml', 'power', 'as', 'ml/1floz', 'mb', '30.0', 'melt"', 'schrader', 'ml/8fl.oz.', 'grams/square', 'gigabit', 'floz(325ml)', 'servings', 'jvc', 'oz(20ml)', 'powersupply', 'floz/86mle', 'madefor', 'blue', '186ml', 'built', '13.4', 'syrup', '0.16', 'ml/3.89', 'eternal', 'ml/2fl', 'oc', 'ml/0.67', 'floz(414', 'bls', 'concentrated', 'state', 'hy', 'ml/0.50', 'csm', 'ml(4oz)', 'optical', 'floz(1pt)473ml', 'horntweeter', 'fl.oz/473ml', 'cssa', '900gb', 'oz(355', 'bottles', 'cu/m', 'fl.oz6ml', 'half', 'oz/8.5', 'psi', 'ml/1fl', 'ultra-powerful', 'sml', 'floz/6m', 'floz/400ml', 'woofer', 'oz/300ml', 'floz/473ml', 'leave-in', 'oz/100gr', 'oz/100', 'car', 'oz355ml', 'load', 'length', 'ml/1fl.oz.', 'level', 'ml/0.35', 'floz(340ml)', 'z', 'ozhalf', 'ozhal', 'hog', 'ml/1.01', 'floz35ml', 'skin.', '72.8-gb', 'digital', 'x4', '14', '8-inch', 'lozenge', 'tool', 'collapsed', 'cerohs', 'ib/g', 'aquarium', 'us_quart', 'possible', 'oz/10ml', 'floz710n', 'floz1qt/946ml', 'together', 'seed', '56', '12', 'yds/215m', 'grain', 'sas', 'floz(340', 'floz472ml']

ValueError: list.remove(x): x not in list

In [37]:
import re
# Cleaning function to remove unwanted characters such as commas, periods, brackets, etc.
def clean_units(units):
    cleaned_units = []
    for unit in units:
        cleaned_unit = re.sub(r'[.,(){}\[\]"\'%]', '', unit)  # Remove unwanted characters
        cleaned_unit = cleaned_unit.strip()  # Remove leading/trailing spaces
        if cleaned_unit:
            cleaned_units.append(cleaned_unit)
    return cleaned_units

# Cleaning the 'badunits' list
cleaned_badunits = clean_units(badUnits)
cleaned_badunits

print(cleaned_badunits)

['unit', 'enough', 'floz', 'cm236', 'steak', '257cm', 'ltd', 'wdusti', '283inch', 'diameter', '35', 'in', 'determine', 'fluid', 'cm**', '222', '3', 'piece', 'newton', '2', '240', 'cubic', 'available', 'air', 'applicable', 'airflow', 'absorbant', 'bulb', 'youthsize', 'cut', '137', 'chicken', '60hz', 'numerical_value', 's6stronge', '5x7', 'cm', 'fluid_ounce', '314/8', 'envirocore', '13', 'gramco', '60', 'not', 'whole', '50', '138', '110cm', 'aey', 'fl0z', '205cm', 'ithum', 'found', '150', 'r3', 'soce', 'numerical', '280', 'cm³', 'gigabyte', 'second', 'hd', 'ibs', 'floz', 'value', 'potato', 'hints', 'bar', 'bend', 'pet', 'in/40', '18', 'ml', 'user', 'net', 'in/40', '24', 'percent', 'fl', 'provided', 'l85', 'color', 'voltage', 'horsepower', 'packets', '175', 'preductoffrance', '6cm', 'and', 'cm354', '23', 'specified', 'gnl', '40', 'compact', 'salad', 'ridgid', '&sour', 'avidpow', 'x18', 'ampere', '5', '819d', '4125-4725', '260cn', '03', 'food', 'deli', 'b/m2', 'ml/1floz', 'degree', 'sleep', 'large', 'floz946ml', '100', 'pack', '200', 'mutant', 'coffee', 'floz', '4mmthickness', 'mango', '18', 'material', 'lers/simples', 'billion', 'btu', 'gm', 'adult', 'trakitri', '1200', 'capsule', '48', 'ml/060floz', 'rpm', 'mushroom', 'e41egs', '5cm', 'bounces', 'hor', '195', 'gsm', 'depth', 'wuxga2000100', '53125', 'in/cm', 'floz473ml', 'softchews', 'to', 'double', '45cm', '1015d', 'brushless', '113g', '1cm', 'tablet', '30cm', '300', 'arty', 'floz330', '40mm', 'provide', 'oz59ml', 'soups&sauces', '150cm/59inch', '98', '136mm', 'l', 'potaocrs', 'lyric', 'lbs', 'floz330ml', '2x', 'tile', 'a312/', 'million', 'pixel', 'fast-absorbing', '102', 'oz', 'hangers', 'cm²', 'data', 'scoops', 'sq', 'btus', '4100', '+', 'speed', '81in', '43mm/169inch', 'cm404', '20cm', 'dollar', 'amp', '322-17', 'dre', 'closed:', 'pcs', 'batteries', 'bags', 'design', 'government', 'exos7e8', '1f1908n', 'blade', 'floz', 'style', 'double-sided', 'cans', 'oz/ml', 'ro', '20e', '42cm', 'miom', 'carcam', '127', 'capacity', 'floz33ml', 'unknown', 'epsom', 'rfx0_e', 'cm²', 'kabab', '200', 'mile', '1763', 'cubic_inch', 'grammes', 'e8', 'wh', 'calopies', '184', 'made', '162', 'left', 'imported', '759d', '55085', 'ca', '20', '0021', 'n/a', 'resealable', 'unit:', 'pages', 'cm/826in', '175cm', 'special', 'handle', 'in/126', 'cm/12in', 'not_applicable', 'cfm/watt', 'drops', '40', 'calorie', 'sheets', 'luggage', 'home', 'work', 'ac90-265v', 'handheld', 'size', 'floz355ml', 'oz/', 'floating_integer', 'height', 'kilocalories', '20w', 'box', 'gigabytes', 'bag', 'lumens', 'hour', '8cm/32', '210cm', 'cms', 'tl/', 'ok', '24t', 'floz355', 'mah', 'milliampere-hour', 'tmakita', 'determined', 'cm280', 'in/490', 'o', '161250va0', 'graphics', '13cm/5inch', 'cm3', 'oz473', '0', '500', 'square', 'umens', 'here', 'miles', '-ej', 'led', '&cheese', 'cm248', 'floz355ml', '67in', 'wisbes', '351n', 'er', 'terabyte', 'clarify', 'grey', '3in', 'froppe', '3x3m', 'skil', 'btu/h', '59', '7mm', 'ml/1oz', 'calories', '28', 'then', 'floz/710ml', 'x1', 'coins', '4cm', '207cm/81', 'determinable', 'k', '01inch', 'pieces', 'me', 'izeeker', 'lbs/705g', 'android100', 'cut', 'fat', 'k230v', 'or', 'fiches', '43/16', '/', 'gb', '14mm', '220v-5400w25a', 'cm/236in', 'cm/inch', 'in/280cm', '1181', '127mm', 'filters', 'ir', 'dog', 'smartest', 'teccpo', '**', 'antennas', 'floz355ml', 'times', 'm³', '178mm', 'integer', '41', 'company', 'k-cuppods', '26', 'omato', 'rotation', '29', '008a', '4-18-288', '110cm', 'from40-120lb', 'hours', 'shcts', 'floz1p1473ml', 'double_thickness', 'singlebrgits', '54', '90mm', '240', 'cm/s²', 'cac', 'resuittast', 'photos', 'ruler', 'light', 'ce', 'playstation', '95', 'compatible', 'mm/inch', '-257mm', 'ychika', 'wood', '725', 'e375474', 'ib', 'g/m2', 'in/36', '37in', 'makita', 'micromillimeter', 'cfm', 'thousand', '1276w', '1', '72', '87cm', 'gps', 'alphasonik', 'packages', '75', '22cm/86in', 'i', 'cm', 'base', 'een', '123cm', 'beam', 'cm/43in', 'popthe', 'tosttos', 'charge', 'morice', 'serving', '95mm', 'jhofa', '07cm/027in', '51cm', 'veodymiun', '08cm/03in', 'acrilico', '/142', '41**', 'ml4oz', 'lumen', 'ml/o60floz', 'family', 'three', '52mm', 'kcal', 'mic', 'micrometre', '63in', 'aa', '29cm', 'r/min', 'cm/in', 'they', '34', 'us', 'cuadro', 'efficiency', '15cm/591', 'a', '36', 'rug', '3x5m', 'cardvr', 'high', '18', 'micrometer', 'information', 'energy', 'be', 'in/34', '24mm', 'mph', '6', '55cm', 'youd', 'lnch', 'nanogram', '-ans', 'defined', '290', '900', 'no', '20cm/787in', '13inch', 'cc/ml', 'milliamp', 'milliampere', 'in/360cm', '15in', 'gr', 'adhesive', 'iov', 'performancee', 'dia', 'your', 'decimal', 'ralevce', '95', '953d', 'f84', '22inch', 'degrees', '40m', '119', 'cm/276in', '12cm/472in', 'oz60', 'l8s', 'count', 'floz355m', '580', 'ram', '16', '2in', '2cm', '5cm/197in', 'can', 'oz80g', '200pcs/set', '8cm', 'ml/371', 'who', '5in', 'mrgo', '17mm', 'x169', 'easy', 'kiss', 'qqty1', 'spin', 'm24', '-off', 'microfarad', 'journeys', '22mm', 'oz355ml', '28cm', '55mm', 'for', 'details', '60x200cm', 'sinocmp', '16', 'ml', '20colors', 'silber', 'lozenges', 'sheet', 'complex', '65cm', 'uueh', '600', 'in/350', 'dc10~30v', 'letter', 'max', 'clear', 'xbox', '7', '10', 'lb/sheet', '25x25m', 'cauno', 'capacity', '8', 'trif', '*', '41cm', 'choking', 'mrc', '*please', 'weight', 'green', '16in/', '60cm', 'moooon', '15mm', '3/5', 'quality', '24cm', 'h', '200cm', '24x19x8cm', 'in/95', 'keto', '1000', '255cm/10in', 'set-up', '136cm', 'filter', '76', 'cubic_foot', 'milliwatt', 'mm/55in', 'cm/34in', 'millile', 'nl', 'floz/207ml', 'cubic_meter', '13500', 'fregc', '25ft', 'soap', 'cm/42', '18/8', '22k', '41', 'mooe3-sntry', 'loads', '19mm', 'ml39', 'enjoy', '7in', '47', 'ovelmp', 'ml025floz', '300w', 'coin', 'with', 'sqft', 'line', 'oraa', '-rc', '/unit', 'bars', '7cm', '10x', 'cm/18', 'cm161', 'pcsd', '?', 'mm3', 'onservadores', 'kilometer', 'sunshine', 'vac', 'cylinder', '1588cm', 'poured', 'save', 'r', 'atx', '&', 'walimex', 'sche', 'helle', '519inch', 'hold', 'adaptor', '130cm/', 'nits', '24', '114mm', 'fish', 'candles', 'oz/200ml', '630', 'lightpack20-21', '95', '40', 'voltage', 'packs', 'uno', 'm3/h', 'strength', 'divider', 'ips', '20', 'units', '197', 'sqft', '55in', 'set', '108inch', 'ko4xs', '31cm', 'truslyour', 'b', 'dc12v', 'cards', '1500pcs85x50cm', '2', '35mm/137in', 'planning', 'n/cm', 'premier', 'fx4', 'proof', '17', 'w', 'would', 'degree_fahrenheit', 'mm³', 'plates', 'pulgadas', 'no_unit', '47mm7185in', 'gold', '60', 'mm/055in', 's', '8cm!', 'fan', 'assembly', 'jolly', 'ml/net', '17inch', '44', 'picture-page', 'year', 'afc', 'ml/8fl', '100cm', 'fully', 'the', 'more', 'bench', 'value', 'coral', 'ultra', 'nch', 'hnc', 'b+', 'c', '25cm8pcs', '225x35', 'usqt1l', 'pieces', '54mm', 'tata', 'in/150', 'pods', 'hack', '18', 'of10-60so', 'lbtimkenload', 'mm/168in', 'mmlt', '120', 'bullet', '78', 'vdc', 'usb', '8mm', 'inch', 'none', '57in', 'unit=cup', 'cm/866in', 'unit', '5mm', 'flozcan', '65subwoofer44', '4', 'pood', 'gram/square_meter', 'untreated', '05', 'verschiedene', '98', 'day', 'ml/05', 'mm/146in', 'apulf-ot', '58in', '5yyayt', 'strips', 'square-meter', '748in', 'bs/100', '30', 'smaller', 'of', '14mm/055in', 'screws', '15cm/59in', 'js', '021', 'profcut', 'oz/g', 'headset', '12v-dc', 'carmo', '8ohm/15vc', '115mm', '30ml', 'undefined', 'e2627', '7952', '57', 'stencil', '227mm', 'oz77ml', 'tomas', '875', 'ierral', '60in', 'teeth', '9/16', '38', 'waterproof', 'bushnel', 'i/w', 'display', '91/8', 'need', 'sketchbook', '8cm/315in', '449cm/177in', 'mil', 'preclsely', 'rap', '47cm', 'x', 'yoga', '12inch/30cm', '11cm/433inch', '13cm/51in', 'cm/295in', 'uto', 'output5v2a', '15', '50cm', 'which', '12*18inch', '10', 'percentage', 'm711', '33', 'odtio', 'makes', 'ml/5fl', 'fc', 'bottle', 'fl', '25', 'ml/o5', 'canvas', '635mm', 'tb', '30x', 'plus', '8m', 'floz/15ml', 'mid', 'dome', 'ml/4oz', 'unit=grams', 'junior3-pack', '5oowatt', 'floz77ml', 'ml/85', 'wires', 'days', 'j', 'floz/237ml', 'floz237', 'bpbaka', 'draw', 'acre', 'tello', 'ml/05oz', 'cc', 'ml/17', 'new', 'cable', 'ratio', 'pump', 'input', 'context', '00', 'page', 'varies', '5v', 'unit=kg', 'mr-black', 'ml/8', 'oz/236ml', 'impedance', '000', 'samsung', '36w', 'scroll', 'floz/473', 'ml/oz', 'floz/946ml', 'yellow', '32', '20gbps', 'grams/sheet', 'oz/sq', '100lbs', 'grams/square-meter', 'lite', 'rider', 'grams/m2', 'bracket', 'blst', 'barrel', 'minute', 'bocina', '5w', 'floz/414ml', '08', 'floz189l', 'bolsas', 'cubic_centimeter', 'r63', 'ml/024', 'byte', 'ssd', 'function', 'minutes', 'sata', 'ibs', 'ml/051floz', 'ml/2', 'millifloz', 'ball', '00000', 'floz/10ml', 'ka', 'shock-proof', 'kids', 'aluminum', 'megahertz', 'floz473ml', 'oz/100g', 'solid', 'ib/400g', 'floz1qt546m', 'dc+33v06a', 'ibsd', 'psi/bar', 'g/lbs', 'cnc', '1/16-3/4', 'oz1l', 'protective', 'almond', 'medium', 'floz/29ml', '3a', 'floz/400', '2-fluid', 'safe', 'pounds@7psi', 'snowballs', 'oz59', 'floz/240ml', 'power', 'as', 'ml/1floz', 'mb', '300', 'melt', 'schrader', 'ml/8floz', 'grams/square', 'gigabit', 'floz325ml', 'servings', 'jvc', 'oz20ml', 'powersupply', 'floz/86mle', 'madefor', 'blue', '186ml', 'built', '134', 'syrup', '016', 'ml/389', 'eternal', 'ml/2fl', 'oc', 'ml/067', 'floz414', 'bls', 'concentrated', 'state', 'hy', 'ml/050', 'csm', 'ml4oz', 'optical', 'floz1pt473ml', 'horntweeter', 'floz/473ml', 'cssa', '900gb', 'oz355', 'bottles', 'cu/m', 'floz6ml', 'half', 'oz/85', 'psi', 'ml/1fl', 'ultra-powerful', 'sml', 'floz/6m', 'floz/400ml', 'woofer', 'oz/300ml', 'floz/473ml', 'leave-in', 'oz/100gr', 'oz/100', 'car', 'oz355ml', 'load', 'length', 'ml/1floz', 'level', 'ml/035', 'floz340ml', 'z', 'ozhalf', 'ozhal', 'hog', 'ml/101', 'floz35ml', 'skin', '728-gb', 'digital', 'x4', '14', '8-inch', 'lozenge', 'tool', 'collapsed', 'cerohs', 'ib/g', 'aquarium', 'us_quart', 'possible', 'oz/10ml', 'floz710n', 'floz1qt/946ml', 'together', 'seed', '56', '12', 'yds/215m', 'grain', 'sas', 'floz340', 'floz472ml']

In [40]:
tempBadUnitsMap2= {
    'floz': 'fluid ounce',
    'cm236': 'centimetre',
    '257cm': 'centimetre',
    '283inch': 'inch',
    'cm**': 'centimetre',
    'cubic': 'cubic foot',
    '60hz': 'watt',
    '5x7': 'inch',
    'cm': 'centimetre',
    'fluid_ounce': 'fluid ounce',
    '110cm': 'centimetre',
    '150': 'millimetre',
    'cm³': 'cubic foot',
    'second': 'cubic foot',
    'ibs': 'pound',
    'value': 'ounce',
    'bar': 'pound',
    'ml': 'millilitre',
    'net': 'gram',
    'percent': 'litre',
    'fl': 'fluid ounce',
    'l85': 'litre',
    'color': 'millilitre',
    'voltage': 'volt',
    'horsepower': 'watt',
    'packets': 'gram',
    'preductoffrance': 'litre',
    '6cm': 'centimetre',
    'cm354': 'centimetre',
    'ridgid': 'gram',
    'b/m2': 'millimetre',
    'ml/1floz': 'fluid ounce',
    'degree': 'millilitre',
    'large': 'cup',
    'floz946ml': 'fluid ounce',
    'pack': 'gram',
    'compact': 'cubic inch',
    '4125-4725': 'millimetre',
    '260cn': 'centimetre',
    'deli': 'gram',
    'coffee': 'cup',
    "ml/060floz": "millilitre",
    "floz473ml": "fluid ounce",
    "floz330": "fluid ounce",
    "oz59ml": "fluid ounce",
    "cubic_inch": "cubic inch",
    "cm²": "centimetre",
    "45cm": "centimetre",
    "20cm": "centimetre",
    "150cm/59inch": "inch",
    "inch": "inch",
    "grammes": "gram",
    "gm": "gram",
    "btu": "watt",
    "wh": "watt",
    "mile": "yard",
    "cm/826in": "inch",
    "175cm": "centimetre",
    "in/126": "inch",
    "cm/12in": "inch",
    "floz355ml": "fluid ounce",
    "oz/": "ounce",
    "20w": "watt",
    "cm280": "centimetre",
    "in/490": "inch",
    "13cm/5inch": "inch",
    "cm3": "centimetre",
    "oz473": "fluid ounce",
    "7mm": "millimetre",
    "ml/1oz": "millilitre",
    "4cm": "centimetre",
    "207cm/81": "inch",
    "43/16": "inch",
    "14mm": "millimetre",
    "cm/236in": "inch",
    "cm/inch": "inch",
    "127mm": "millimetre",
    "178mm": "millimetre",
    "110cm": "centimetre",
    "floz1p1473ml": "fluid ounce",
    "90mm": "millimetre",
    "cm/s²": "unknown",
    "g/m2": "gram",
    "in/36": "inch",
    "37in": "inch",
    "cm/43in": "inch",
    "95mm": "millimetre",
    "07cm/027in": "inch",
    "51cm": "centimetre",
    "08cm/03in": "inch",
    "ml4oz": "millilitre",
    "ml/o60floz": "millilitre",
    "52mm": "millimetre",
    "63in": "inch",
    "29cm": "centimetre",
    "15cm/591": "inch",
    "20cm/787in": "inch",
    "13inch": "inch",
    "cc/ml": "millilitre",
    "milliamp": "unknown",
    "milliampere": "unknown",
    "15in": "inch",
    "22inch": "inch",
    "cm/276in": "inch",
    "12cm/472in": "inch",
    "floz355m": "fluid ounce",
    "2in": "inch",
    "5cm/197in": "inch",
    "oz80g": "ounce",
    "8cm": "centimetre",
    "ml/371": "millilitre",
    "17mm": "millimetre",
    "22mm": "millimetre",
    "oz355ml": "fluid ounce",
    "28cm": "centimetre",
    "55mm": "millimetre",
    "65cm": "centimetre",
    "16in/": "inch",
    "60cm": "centimetre",
    "15mm": "millimetre",
    "41cm": "centimetre",
    "24cm": "centimetre",
    "200cm": "centimetre",
    "ml/371": "millilitre",
    "mm/55in": "inch",
    "cm/34in": "inch",
    "floz/207ml": "fluid ounce",
    "cubic_meter": "litre",
    "25ft": "yard",
    "cm/42": "centimetre",
    "7cm": "centimetre",
}

In [43]:
import re

# Escaping keys for safe regex use
escaped_map = {re.escape(key): value for key, value in tempBadUnitsMap2.items()}

# Replace values in 'entity_unit' using the escaped regex patterns
for key, value in escaped_map.items():
    df2['entity_unit'] = df2['entity_unit'].replace(r'\b{}\b'.format(key), value, regex=True)

# Step 2: Filter the DataFrame to include only rows where 'entity_unit' is in goodUnits
# df3 = df2[df2['entity_unit'].isin(goodUnits)]
# print(df3.shape)

(84770, 4)

np.int64(0)

In [47]:
df3 = df2.copy()
print(df3.shape)

df3['entity_unit'].isnull().sum()
df3['entity_unit'].isin(goodUnits).sum()

(131175, 4)

np.int64(84770)

In [48]:
df110= df2[df2['entity_unit'].isin(badUnits)]
print(df110.shape)

(45983, 4)

In [35]:
updatedDfBadUnitsMap = {}

# Sort the keys of dfBadUnitsMap by length in descending order
sortedKeys = sorted(dfBadUnitsMap.keys(), key=len, reverse=True)
print(sortedKeys)

for unit in badUnits:
    for key in sortedKeys:
        if unit != 'unit' and key in unit:
            updatedDfBadUnitsMap[unit] = dfBadUnitsMap[key]
            break  # Stop after the first match to prioritize larger words

# Print the length and contents of the updated dictionary
print(len(updatedDfBadUnitsMap))
print(updatedDfBadUnitsMap)

# Get unique values
unq = set(updatedDfBadUnitsMap.values())

for v in unq:
    if v not in goodUnits:
        print(v)

# Count unique values
count_unique = len(unq)
print(count_unique)

['millimetres', 'centimetres', 'millimeters', 'centimeters', 'millilitres', 'millimeter', 'centimeter', 'milligrams', 'milliliter', 'kilograms', 'gallons', 'pounds', 'ounces', 'meters', 'liters', 'inches', 'meter', 'grams', 'liter', 'volts', 'watts', 'yards', 'feet', 'gal', 'cm', 'oz', 'in', 'lb', 'qt', 'kg', 'mg', 'ft', 'mm', 'm', 'g']
495
{'enough': 'gram', 'floz': 'ounce', 'cm(23.6")': 'centimetre', '25.7.cm"': 'centimetre', '2.83inch': 'inch', 'diameter': 'metre', 'in.': 'inch', 'determine': 'inch', 'cm**': 'centimetre', 'bulb': 'pound', 'numerical_value': 'metre', 's6%stronge': 'gram', 'cm",': 'centimetre', 'gramco': 'metre', '110cm': 'centimetre', '20.5cm': 'centimetre', 'ithum': 'metre', 'numerical': 'metre', 'cm³': 'centimetre', 'gigabyte': 'gram', 'fl.oz.': 'ounce', 'hints': 'inch', 'in/40': 'inch', 'ml': 'metre', 'in/4.0': 'inch', '[voltage': 'gram', '6cm': 'centimetre', 'cm(35,4")': 'centimetre', 'gnl': 'gram', 'compact': 'metre', 'ridgid': 'gram', 'ampere': 'metre', 'b/m2': 'metre', 'ml/1fl.oz': 'ounce', 'degree': 'gram', 'large': 'gram', 'floz946ml': 'ounce', 'mutant': 'metre', 'floz.': 'ounce', '4mm(thickness)': 'millimetre', 'mango': 'metre', 'material"': 'metre', 'lers/simples': 'metre', 'gm': 'metre', 'ml/0.60fl.oz.': 'ounce', 'rpm': 'metre', 'mushroom': 'metre', 'e41egs': 'gram', '5cm': 'centimetre', 'bounces': 'ounce', 'gsm': 'metre', 'wuxga2,000100': 'gram', 'in/cm': 'centimetre', 'floz(473ml)': 'ounce', 'softchews': 'foot', '45cm': 'centimetre', '113g': 'gram', '1cm': 'centimetre', '30cm': 'centimetre', 'floz330': 'ounce', '40mm': 'millimetre', 'oz59ml': 'ounce', '150cm/59inch': 'centimetre', '136mm': 'millimetre', 'lbs': 'pound', 'floz330ml': 'ounce', 'million': 'metre', 'fast-absorbing': 'inch', 'oz.': 'ounce', 'hangers': 'gram', 'cm²': 'centimetre', '8.1in': 'inch', '43mm/1.69inch': 'inch', 'cm40.4': 'centimetre', '20cm': 'centimetre', 'amp': 'metre', 'bags': 'gram', 'design': 'gram', 'government': 'metre', 'fl.oz': 'ounce', 'oz/ml': 'ounce', '42cm': 'centimetre', 'miom': 'metre', 'carcam': 'metre', 'floz33ml': 'ounce', 'epsom': 'metre', 'cm²",': 'centimetre', 'mile': 'metre', 'cubic_inch': 'inch', 'grammes': 'millimetre', 'made': 'metre', 'left': 'foot', 'imported': 'metre', 'pages': 'gram', 'cm/8.26in': 'centimetre', '17.5cm': 'centimetre', 'in/12.6': 'inch', 'cm/12in': 'centimetre', 'cfm/watt': 'metre', 'luggage': 'gram', 'home': 'metre', 'floz(355ml': 'ounce', 'oz/': 'ounce', 'floating_integer': 'inch', 'height': 'gram', 'gigabytes': 'gram', 'bag': 'gram', 'lumens': 'metre', '8cm/3.2"': 'centimetre', '210cm': 'centimetre', 'cms': 'centimetre', 'floz355': 'ounce', 'mah': 'metre', 'milliampere-hour': 'metre', 'tmakita': 'metre', 'determined': 'inch', 'cm28.0': 'centimetre', 'in/49.0': 'inch', 'graphics': 'gram', '13cm/5inch': 'centimetre', 'cm3': 'centimetre', 'oz(473': 'ounce', 'umens': 'metre', 'miles': 'metre', 'cm24.8': 'centimetre', 'floz355ml': 'ounce', '6.7in': 'inch', 'grey': 'gram', '3in': 'inch', '3x3m': 'metre', '7mm': 'millimetre', 'ml/1oz': 'ounce', 'floz/710ml': 'ounce', 'coins': 'inch', '.4cm': 'centimetre', '20.7cm/8.1': 'centimetre', 'determinable': 'inch', '0.1inch': 'inch', 'me': 'metre', 'lbs/705g': 'pound', 'gb': 'gram', '14mm': 'millimetre', 'cm/2.36in': 'centimetre', 'cm/inch': 'centimetre', 'in/28.0cm': 'centimetre', '127mm': 'millimetre', 'dog': 'gram', 'smartest': 'metre', 'floz(355ml)': 'ounce', 'times': 'metre', 'm³': 'metre', '178mm': 'millimetre', 'integer': 'inch', 'company': 'metre', 'omato': 'metre', '11.0cm': 'centimetre', 'from40-120lb': 'pound', 'floz1p1473ml': 'ounce', 'singlebrgits': 'inch', '90mm': 'millimetre', 'cm/s²': 'centimetre', 'light': 'gram', 'compatible': 'metre', 'mm/inch': 'inch', '-257mm': 'millimetre', 'g/m2': 'metre', 'in/36': 'inch', '3.7in)': 'inch', 'makita': 'metre', 'micromillimeter': 'millimetre', 'cfm': 'metre', '87cm': 'centimetre', 'gps': 'gram', 'packages': 'gram', '22cm/8.6in': 'centimetre', 'cm.': 'centimetre', '123cm': 'centimetre', 'beam': 'metre', 'cm/4.3in': 'centimetre', 'charge': 'gram', 'morice': 'metre', 'serving': 'inch', '95mm': 'millimetre', '0.7cm/0.27in': 'centimetre', '5.1cm': 'centimetre', 'veodymiun': 'metre', '0.8cm/0.3in': 'centimetre', 'ml4oz': 'ounce', 'lumen': 'metre', 'ml/o.60fl.oz.': 'ounce', 'family': 'metre', '52mm': 'millimetre', 'mic': 'metre', 'micrometre': 'metre', '6.3in': 'inch', '29cm': 'centimetre', 'r/min': 'inch', 'cm/in': 'centimetre', '15cm/5.91"': 'centimetre', 'rug': 'gram', '3x5m': 'metre', 'high': 'gram', 'micrometer': 'metre', 'information': 'inch', 'energy': 'gram', 'in/34': 'inch', '24mm': 'millimetre', 'mph': 'metre', '55cm': 'centimetre', 'nanogram': 'metre', 'defined': 'inch', '20cm/7.87in': 'centimetre', '1.3inch': 'inch', 'cc/ml': 'metre', 'milliamp': 'metre', 'milliampere': 'metre', 'in/36.0cm': 'centimetre', '15in': 'inch', 'gr': 'gram', 'performancee': 'metre', 'decimal': 'metre', '2.2inch': 'inch', 'degrees': 'gram', '4.0m': 'metre', 'cm/2.76in': 'centimetre', '12cm/4.72in': 'centimetre', 'oz60': 'ounce', 'floz355m': 'ounce', 'ram': 'metre', '2in': 'inch', '2cm': 'centimetre', '5cm/1.97in': 'centimetre', 'oz80g': 'ounce', '8cm': 'centimetre', 'ml/3.71': 'metre', '5in': 'inch', 'mr.go': 'metre', '17mm': 'millimetre', 'qqty1': 'quart', 'spin': 'inch', 'm24': 'metre', 'microfarad': 'metre', '22mm': 'millimetre', 'oz(355ml)': 'ounce', '28cm': 'centimetre', '55mm': 'millimetre', '60x200cm': 'centimetre', 'sinocmp': 'centimetre', '(ml)': 'metre', 'silber': 'pound', 'lozenges': 'ounce', 'complex': 'metre', '6.5cm': 'centimetre', 'in/35.0': 'inch', 'max': 'metre', 'lb/sheet': 'pound', '2.5x2.5m': 'metre', '41cm': 'centimetre', 'choking': 'inch', 'mrc': 'metre', 'weight': 'gram', 'green': 'gram', '16in/': 'inch', '60cm': 'centimetre', 'moooon': 'metre', '15mm': 'millimetre', '24cm': 'centimetre', '200cm': 'centimetre', '24x19x8cm': 'centimetre', 'in/95': 'inch', '25.5cm/10in': 'centimetre', '13.6cm': 'centimetre', 'milliwatt': 'metre', 'mm/5.5in': 'inch', 'cm/3.4in': 'centimetre', 'millile': 'metre', 'floz/207ml': 'ounce', 'cubic_meter': 'metre', 'fregc': 'gram', '2.5ft': 'foot', 'cm/4.2': 'centimetre', 'mooe3-sntry': 'metre', '19mm': 'millimetre', 'ml(3.9': 'metre', '7in': 'inch', 'ovelmp': 'metre', 'ml0.25fl.oz': 'ounce', 'coin': 'inch', 'sq.ft': 'foot', 'line': 'inch', '7cm': 'centimetre', 'cm/18': 'centimetre', 'cm(16.1)': 'centimetre', 'mm3': 'millimetre', 'kilometer': 'metre', 'sunshine': 'inch', 'cylinder': 'inch', '(15.88cm)': 'centimetre', 'walimex': 'metre', '5.19inch': 'inch', '130cm/': 'centimetre', '(114mm)': 'millimetre', 'oz/200ml': 'ounce', 'lightpack20-21': 'gram', 'voltage': 'gram', 'm3/h': 'metre', 'strength': 'gram', 'sq.ft.': 'foot', '5.5in': 'inch', '108inch': 'inch', '31cm': 'centimetre', '1500pcs85x50cm': 'centimetre', '35mm/1.37in': 'inch', 'planning': 'inch', 'n/cm': 'centimetre', 'premier': 'metre', 'degree_fahrenheit': 'gram', 'mm³': 'millimetre', 'pulgadas': 'gram', '47mm71.85in': 'inch', 'gold': 'gram', 'mm/0.55in': 'inch', '8cm!': 'centimetre', 'assembly': 'metre', 'ml/net': 'metre', '1.7inch': 'inch', 'picture-page': 'gram', 'ml/8fl': 'metre', '100cm': 'centimetre', 'more': 'metre', '2.5cm(8pcs)': 'centimetre', 'u.s.qt(1l)': 'quart', '54mm': 'millimetre', 'in/150': 'inch', 'lbtimkenload': 'pound', 'mm/1.68in': 'inch', 'mmlt': 'millimetre', '8mm': 'millimetre', 'inch",': 'inch', '5.7in': 'inch', 'cm/8.66in': 'centimetre', '5mm': 'millimetre', 'flozcan': 'ounce', 'gram/square_meter': 'metre', 'ml/0.5': 'metre', 'mm/1.46in': 'inch', '5.8in': 'inch', 'square-meter': 'metre', '7.48in': 'inch', 'smaller': 'metre', '14mm/0.55in': 'inch', '15cm/5.9in': 'centimetre', 'oz/g': 'ounce', 'carmo': 'metre', '8ohm/15vc': 'metre', '115mm': 'millimetre', '30ml': 'metre', 'undefined': 'inch', '227mm': 'millimetre', 'oz(77ml)': 'ounce', 'tomas': 'metre', '60in': 'inch', '8cm/3.15in': 'centimetre', "44.9cm/17.7in'": 'centimetre', 'mil': 'metre', '47cm': 'centimetre', 'yoga': 'gram', '12inch/30cm': 'centimetre', '11cm/4.33inch': 'centimetre', '13cm/5.1in': 'centimetre', 'cm/2.95in': 'centimetre', '(50cm)': 'centimetre', '12*18inch': 'inch', 'percentage': 'gram', 'm711': 'metre', 'makes': 'metre', 'ml/5fl': 'metre', 'ml/o.5': 'metre', '6.35mm': 'millimetre', '8m': 'metre', 'fl.oz/15ml': 'ounce', 'mid': 'metre', 'dome': 'metre', 'ml/4oz': 'ounce', 'unit=grams': 'gram', 'fl.oz(77ml': 'ounce', 'ml/8.5': 'metre', 'floz/237ml': 'ounce', 'floz(237': 'ounce', 'ml/0.5oz': 'ounce', 'ml/1.7': 'metre', 'pump': 'metre', 'input': 'inch', 'page': 'gram', 'unit=kg': 'kilogram', 'mr-black': 'metre', 'ml/8': 'metre', 'oz/236ml': 'ounce', 'impedance': 'metre', 'samsung': 'metre', 'floz/473': 'ounce', 'ml/oz': 'ounce', 'floz/946ml': 'ounce', '20gbps': 'gram', 'grams/sheet': 'gram', 'oz/sq': 'ounce', '100lbs': 'pound', 'grams/square-meter': 'metre', 'grams/m2': 'gram', 'minute': 'inch', 'bocina': 'inch', 'floz/414ml': 'ounce', 'floz(1.89l)': 'ounce', 'cubic_centimeter': 'centimetre', 'ml/0.24': 'metre', 'minutes': 'inch', 'ml/0.51fl.oz.': 'ounce', 'ml/2': 'metre', 'millifloz': 'ounce', 'floz/10ml': 'ounce', 'aluminum': 'inch', 'megahertz': 'metre', 'floz473ml': 'ounce', 'oz/100g': 'ounce', 'ib/400g': 'gram', 'floz1qt546m': 'ounce', 'g/lbs': 'pound', 'oz1l': 'ounce', 'almond': 'metre', 'medium': 'metre', 'floz/29ml': 'ounce', 'floz/400': 'ounce', 'pounds@7psi': 'pound', 'oz59': 'ounce', 'floz/240ml': 'ounce', 'ml/1floz': 'ounce', 'mb': 'metre', 'melt"': 'metre', 'ml/8fl.oz.': 'ounce', 'grams/square': 'gram', 'gigabit': 'gram', 'floz(325ml)': 'ounce', 'servings': 'inch', 'oz(20ml)': 'ounce', 'floz/86mle': 'ounce', 'madefor': 'metre', '186ml': 'metre', 'ml/3.89': 'metre', 'ml/2fl': 'metre', 'ml/0.67': 'metre', 'floz(414': 'ounce', 'ml/0.50': 'metre', 'csm': 'metre', 'ml(4oz)': 'ounce', 'floz(1pt)473ml': 'ounce', 'fl.oz/473ml': 'ounce', '900gb': 'gram', 'oz(355': 'ounce', 'cu/m': 'metre', 'fl.oz6ml': 'ounce', 'oz/8.5': 'ounce', 'ml/1fl': 'metre', 'sml': 'metre', 'floz/6m': 'ounce', 'floz/400ml': 'ounce', 'oz/300ml': 'ounce', 'floz/473ml': 'ounce', 'leave-in': 'inch', 'oz/100gr': 'ounce', 'oz/100': 'ounce', 'oz355ml': 'ounce', 'length': 'gram', 'ml/1fl.oz.': 'ounce', 'ml/0.35': 'metre', 'floz(340ml)': 'ounce', 'ozhalf': 'ounce', 'ozhal': 'ounce', 'hog': 'gram', 'ml/1.01': 'metre', 'floz35ml': 'ounce', 'skin.': 'inch', '72.8-gb': 'gram', 'digital': 'gram', '8-inch': 'inch', 'lozenge': 'ounce', 'ib/g': 'gram', 'aquarium': 'metre', 'oz/10ml': 'ounce', 'floz710n': 'ounce', 'floz1qt/946ml': 'ounce', 'together': 'gram', 'yds/215m': 'metre', 'grain': 'inch', 'floz(340': 'ounce', 'floz472ml': 'ounce'}
10

In [36]:
import re

def is_valid_regex_key(key):
    try:
        re.compile(r'\b{}\b'.format(re.escape(key)))
        return True
    except re.error:
        return False

# Filter out invalid keys
filtered_updatedDfBadUnitsMap = {key: value for key, value in updatedDfBadUnitsMap.items() if is_valid_regex_key(key)}

# Now you can safely use the filtered map
for key, value in filtered_updatedDfBadUnitsMap.items():
    df2['entity_unit'] = df2['entity_unit'].replace(r'\b{}\b'.format(re.escape(key)), value, regex=True)

In [433]:
# import re

# # df47 = df49.copy()

# for key, value in updatedDfBadUnitsMap.items():
#     # Escape special regex characters in the key
#     escaped_key = re.escape(key)
#     df2['entity_unit'] = df2['entity_unit'].replace(r'\b{}\b'.format(escaped_key), value, regex=True)

# # df46 = df2[df2['entity_unit'].isin(goodUnits)]
# # print(df46.shape)
# # df46.head()

# df2.head()

In [50]:
print(df2.shape)
print(len(df2['entity_unit'].unique()))
df2['entity_unit'].unique()

(131175, 4)
726

array(['inch', 'centimetre', 'unit', 'volt', 'kilogram', 'pound', None,
       'gram', 'millimetre', 'watt', 'ounce', 'centimetre(23.6")',
       'steak', '25.7.centimetre"', 'ton', 'ltd', '', 'wdusti', 'metre',
       'foot', '3.5"', 'inch.', 'fluid', 'centimetre**', 'millilitre',
       '22.2', '3', 'piece', 'newton', '2', 'milligram', '24.0',
       'cubic foot foot', 'available', 'air', 'applicable', 'airflow',
       'absorbant', 'youthsize', 'cut', '1.37', 'chicken', 'litre',
       'centimetre",', 'fluid ounce', '3.14/8,', 'envirocore', 'cup',
       '13"', '6.0', 'not', 'kilowatt', 'whole', '5.0', '13.8', 'aey',
       'fl0z', 'found', '15.0', 'r3', 'soce', '28.0', 'hd',
       'fluid ounce.ounce.', 'quart', 'ounce]', 'potato', 'bend', 'pet',
       'inch/40', '18"', 'user', 'inch/4.0', '24%', 'provided', '[gram',
       '17.5', '"', 'and', 'centimetre(35,4")', '23', 'specified', '40',
       'salad', '&sour', 'avidpow', 'x18', '5', '8.19d', '41.25-47.25',
       '03', 'food', 'metre/1fl.ounce', 'sleep', '100', '20.0', 'gallon',
       'ounce.', '4mm(thickness)', '18', 'material"', 'billion', 'adult',
       'trakitri', '120.0', 'capsule', '48', 'metre/0.60fl.ounce.', 'hor',
       '195', 'depth', '53125', 'inch/centimetre', '.', 'ounce(473ml)',
       'to', 'double', '10.15d', 'brushless', 'tablet', '{30.0}', 'arty',
       'provide', 'soups&sauces', '9.8', 'l', 'potaocrs', 'lyric',
       'millivolt', '2x', 'tile', 'a312/', 'pixel', '10.2"', 'data',
       'scoops', 'sq', 'btus', '4100', '+', 'speed', 'dollar', '322-17',
       'dre', 'closed:', 'pcs', 'batteries', 'exos7e8', '1f1908n',
       'blade', 'fluid ounce.ounce', 'style', 'double-sided', 'cans',
       'ounce/metre', 'ro', '2.0e', '12.7"', 'capacity"', 'unknown',
       'rfx0_e', 'kabab', '200', '17.63"', 'e8.', 'calopies', '184',
       '162', '7.59d', '55085', 'ca', '20', '0,021', 'n/a', 'resealable',
       'unit:', 'centimetre/8.26in', '17.centimetre', 'special', 'handle',
       'inch/12.6', 'centimetre/12in', 'not_applicable', 'drops', '40%',
       'calorie', 'sheets', 'work', 'ac90-265v', 'handheld', 'size',
       'ounce(355ml', 'ounce/', 'kilocalories', 'box', 'hour',
       'centimetre/3.2"', 'tl/', 'ok', '24t', 'inch/49.0', 'o',
       '161250va0', 'ounce(473', '0', '50.0', 'square', 'here', '-ej',
       'led', '&cheese', 'wisbes', '3.51n', 'er', 'terabyte', 'clarify',
       'froppe', 'skil,...', 'watt/h', '5.9,', 'metre/1oz', 'calories',
       '28"', 'then', 'ounce/710ml', 'x1', '.centimetre', 'k', 'pieces',
       'izeeker', 'pound/705g', 'android10.0', 'cu.t', 'fat', 'k230v',
       'or', 'fiches', 'inch"', '/', '220v-5400w25a', 'centimetre/2.36in',
       'centimetre/inch', 'inch/28.0cm', '1181', 'filters', 'ir',
       'teccpo', '**', 'antennas', 'ounce(355ml)', '41"', 'k-cuppods',
       '26', 'rotation', '29', '0.08a', '4-18-288', 'hours', 'shcts',
       'double_thickness', '54', '240', 'centimetre/s²', 'cac',
       'resuittast', 'photos', 'ruler', 'ce', 'playstation', '9.5"',
       'millimetre/inch', '-257mm', 'ychika', 'wood', '7.25', 'e375474',
       'ib', 'gram/m2', 'inch/36', '3.inch)', 'thousand', '12.76w', '1',
       '72"', 'alphasonik', '7.5', 'i', 'centimetre.', 'base', 'een',
       'centimetre/4.inch', 'popthe', 'tosttos', 'jhofa', '5.centimetre',
       '0.centimetre/0.inch', 'acrilico', '/1.42".', '4.1"**', ',',
       'metre/o.60fl.ounce.', 'three', 'kcal', '6.inch', 'aa', 'they',
       '34', 'us', 'cuadro', 'efficiency', '15cm/5.91"', 'a', '36',
       'cardvr', '1.8', 'be', 'inch/34', '6', "you'd", 'lnch', '-ans',
       '29.0', '90.0,', 'no', 'centimetre/7.87in', 'cc/metre',
       'inch/36.0cm', 'adhesive', 'iov', 'dia', 'your', 'ralevce', '95',
       '9.53d', 'f8"4', '11.9,', 'centimetre/2.76in', 'l8s', 'count',
       'yard', '58.0', '1.6]', 'centimetre/1.97in', 'can', '200pcs/set',
       'metre/3.71', 'who', 'x16.9', 'easy', 'kiss', '-off', 'journeys',
       'for', 'details', "16'", '(metre)', '20colors', 'sheet',
       '6.centimetre', 'uueh', '60.0', 'inch/35.0', 'dc10~30v', 'letter',
       'clear', 'xbox', '7', '10"', 'pound/sheet', 'cauno', 'capacity',
       '8"', 'trif', '*', '*please', '16in/', '3/5', 'quality', 'h',
       'inch/95', 'keto', '100.0', '25.centimetre/10in', 'set-up',
       '13.centimetre', 'filter', '7.6', 'cubic_foot',
       'millimetre/5.inch', 'centimetre/3.4in', 'nl', 'ounce/207ml',
       '13500', 'soap', 'centimetre/4.2', '18/8', '2.2k', '41', 'loads',
       'metre(3.9', 'enjoy', '4.7', 'ml0.25fl.ounce', '300w', 'with',
       'sq.foot', 'oraa', '-rc', '/unit', 'bars', '10x', 'centimetre/18',
       'centimetre(16.1)', 'pcsd', '?', 'onservadores', 'vac',
       '(15.88cm)', 'poured', 'save', 'r', 'atx', '&', 'sche', 'helle',
       'hold', 'adaptor', '130cm/', 'nits', '24"', '(114mm)', 'fish',
       'candles', 'ounce/200ml', '6.30"', '9.5', '40"', 'packs', "uno'",
       'divider', 'ips', '20"', 'units', '19.7', 'sq.foot.', '5.inch',
       'set', "k.o.4x's", 'truslyour', 'b', 'dc12v', 'cards', '2"',
       'n/centimetre', 'fx4', 'proof', '1.7', 'w', 'would', 'plates',
       'no_unit', '60', 'millimetre/0.55in', 's', 'centimetre!', 'fan',
       'jolly', 'metre/gram', '4.4', 'year', 'afc', 'metre/8fl', 'fully',
       'the', 'bench', 'coral', 'ultra', 'nch', 'hnc', 'b+', 'c',
       '2.centimetre(8pcs)', '2.25x3.5"', 'u.s.quart(1l)', 'piece(s)',
       'tata', 'inch/millimetre', 'pods', 'hack', '1.8"', 'of10-60,so',
       'millimetre/1.68in', '120', 'bullet', '7,8', 'vdc', 'usb',
       'inch",', 'none', 'unit=cup', 'centimetre/8.66in', '{unit}',
       '6.5subwoofer44', '4', 'pood', 'untreated', '0.5"', 'verschiedene',
       '9.8"', 'day', 'metre/0.5', 'millimetre/1.46in', 'apulf-ot',
       '5yyayt', 'strips', 'square-metre', 'bs/100', '30"', 'of',
       'screws', 'js', '0.21,', 'profcut', 'ounce/gram', 'headset',
       '12v-dc', 'e2627', '79.52"', '5.7', 'stencil', 'ounce(77ml)',
       '8.75', 'ierral', 'teeth', '9/16"', '38', 'waterproof', 'bushnel',
       'i/w', 'display', '91/8"', 'need', 'sketchbook',
       'centimetre/3.inch', "44.9cm/17.inch'", 'preclsely', 'rap', 'x',
       '12inch/centimetre', 'centimetre/2.95in', 'uto', 'output5v2a',
       '15', '(50cm)', 'which', '10', '33"', 'odtio', 'metre/5fl', 'fc',
       'bottle', 'fluid ounce.', '25', 'metre/o.5', 'canvas', 'tb', '30x',
       'plus', 'fluid ounce.ounce/15ml', 'metre/4oz', 'unit=gram',
       'junior3-gram', '5oowatt', 'fluid ounce.ounce(77ml', 'metre/8.5',
       'wires', 'days', 'j', 'ounce/237ml', 'ounce(237', 'bpbaka', 'draw',
       'acre', 'tello', 'metre/0.5oz', 'cc', 'metre/1.7', 'new', 'cable',
       'ratio', 'context', '00', 'varies]', '5v', 'unit=kilogram',
       'metre/8', 'ounce/236ml', '000', '36w', 'scroll', 'ounce/473',
       'metre/ounce', 'ounce/946ml', 'yellow', '32', 'gram/sheet',
       'ounce/sq', 'gram/square-metre', 'lite', 'rider', 'bracket',
       'blst', 'barrel', 'kilovolt', '5w', 'ounce/414ml', '08',
       'ounce(1.89l)', 'bolsas', 'r63', 'metre/0.24', 'byte', 'ssd',
       'function', 'sata', 'pound.', 'metre/0.51fl.ounce.', 'metre/2',
       'ball', '00000', 'ounce/10ml', 'ka', 'shock-proof', 'kids',
       'ounce/100g', 'solid', 'dc+3.3v0.6a', 'ibsd', 'psi/pound',
       'gram/pound', 'cnc', '1/16-3/4', 'protective', 'ounce/29ml', '3a',
       'ounce/400', '2-fluid', 'pint', 'safe', 'pound@7psi', 'snowballs',
       'ounce/240ml', 'power', 'as', 'metre/1floz', '30.0', 'melt"',
       'schrader', 'metre/8fl.ounce.', 'gram/square', 'ounce(325ml)',
       'jvc', 'ounce(20ml)', 'powersupply', 'ounce/86mle', 'blue',
       'built', '13.4', 'syrup', '0.16', 'metre/3.89', 'eternal',
       'metre/2fl', 'oc', 'metre/0.67', 'ounce(414', 'bls',
       'concentrated', 'state', 'hy', 'metre/0.50', 'metre(4oz)',
       'optical', 'ounce(1pt)473ml', 'horntweeter',
       'fluid ounce.ounce/473ml', 'cssa', 'ounce(355', 'bottles',
       'cu/metre', 'half', 'ounce/8.5', 'psi', 'metre/1fl',
       'ultra-powerful', 'ounce/6m', 'ounce/400ml', 'woofer',
       'ounce/300ml', 'ounce/473ml', 'leave-inch', 'ounce/100gr',
       'ounce/100', 'car', 'load', 'metre/1fl.ounce.', 'level',
       'metre/0.35', 'ounce(340ml)', 'z', 'metre/1.01', 'skin.',
       '72.8-gram', 'x4', '14', 'tool', 'collapsed', 'cerohs', 'ib/gram',
       'us_quart', 'possible', 'seed', '56', '12', 'sas', 'ounce(340'],
      dtype=object)

In [51]:
# Function to check and update rows
def check_and_update(row):
    if row['entity_unit'] not in goodUnits:
        row['entity_value'] = np.nan
        row['entity_unit'] = np.nan
        row['ans_entity_val'] = np.nan
    return row

# Apply the function to each row
df2 = df2.apply(check_and_update, axis=1)

print(df2.shape)
df2.head(20)

(131175, 4)

    index   ans_entity_val entity_value entity_unit
0       0        78.0 inch         78.0        inch
1       1          42.0 cm         42.0  centimetre
2       2         200.0 cm        200.0  centimetre
3       3              NaN          NaN         NaN
4       4              NaN          NaN         NaN
5       5          90.0 cm         90.0  centimetre
6       6         10.50 cm        10.50  centimetre
7       7         1.4 inch          1.4        inch
8       8  40.0 centimetre         40.0  centimetre
9       9  40.0 centimetre         40.0  centimetre
10     10              NaN          NaN         NaN
11     11  30.6 centimetre         30.6  centimetre
12     12         4.3 inch          4.3        inch
13     13         4.3 inch          4.3        inch
14     14         4.3 inch          4.3        inch
15     15              NaN          NaN         NaN
16     16              NaN          NaN         NaN
17     17              NaN          NaN         NaN
18     18              NaN          NaN         NaN
19     19       208.0 volt        208.0        volt

In [52]:
print(df2.shape)
print(len(df2['entity_unit'].unique()))
print(df2['entity_unit'].unique())

df2['entity_unit'].isnull().sum()

(131175, 4)
25
['inch' 'centimetre' nan 'volt' 'kilogram' 'pound' 'gram' 'millimetre'
 'watt' 'ounce' 'ton' 'metre' 'foot' 'millilitre' 'milligram' 'litre'
 'fluid ounce' 'cup' 'kilowatt' 'quart' 'gallon' 'millivolt' 'yard'
 'kilovolt' 'pint']

np.int64(46405)

In [53]:
df2.to_csv("./final_test_output_eda_interm2.csv", index=False)

In [55]:
# # Function to check if a value is not a float and not null
# def is_not_float_or_null(value):
#     if pd.isnull(value):
#         return False
#     try:
#         float(value)
#         return False
#     except ValueError:
#         return True

# # Apply the function to filter rows
# filtered_df = df2[df2['entity_value'].apply(is_not_float_or_null)]

# print(filtered_df.shape)
# filtered_df.head()

# # Update the entity_value and entity_unit columns for the filtered rows
# df2.loc[df2['entity_value'].apply(is_not_float_or_null), ['entity_value', 'entity_unit']] = ''

# print(df2.shape)
# df2.head(20)


import pandas as pd

# Function to check if a value is not a float or not null and to convert scientific notation to float
def process_value(value):
    if pd.isnull(value):
        return None, True  # Return None to mark it as null
    try:
        # Convert value to float if it's a valid float (including scientific notation)
        float_value = float(value)
        return float_value, False  # Valid float, so not in the filtered list
    except ValueError:
        return value, True  # Not a float, so it should be in the filtered list

# Apply the function to the 'entity_value' column
df2[['processed_value', 'is_not_float_or_null']] = df2['entity_value'].apply(lambda x: pd.Series(process_value(x)))

# Filter rows where 'is_not_float_or_null' is True
filtered_df = df2[df2['is_not_float_or_null']]

print(filtered_df.shape)
print(filtered_df.head())

# Update the 'entity_value' and 'entity_unit' columns for the filtered rows
df2.loc[df2['is_not_float_or_null'], ['entity_value', 'entity_unit']] = ''

print(df2.shape)
df2.head(20)

(46907, 6)
    index ans_entity_val entity_value entity_unit processed_value  \
3       3            NaN          NaN         NaN            None
4       4            NaN          NaN         NaN            None
10     10            NaN          NaN         NaN            None
15     15            NaN          NaN         NaN            None
16     16            NaN          NaN         NaN            None

    is_not_float_or_null
3                   True
4                   True
10                  True
15                  True
16                  True
(131175, 6)
    index   ans_entity_val entity_value entity_unit processed_value  \
0       0        78.0 inch         78.0        inch            78.0
1       1          42.0 cm         42.0  centimetre            42.0
2       2         200.0 cm        200.0  centimetre           200.0
3       3              NaN                                     None
4       4              NaN                                     None
5       5          90.0 cm         90.0  centimetre            90.0
6       6         10.50 cm        10.50  centimetre            10.5
7       7         1.4 inch          1.4        inch             1.4
8       8  40.0 centimetre         40.0  centimetre            40.0
9       9  40.0 centimetre         40.0  centimetre            40.0
10     10              NaN                                     None
11     11  30.6 centimetre         30.6  centimetre            30.6
12     12         4.3 inch          4.3        inch             4.3
13     13         4.3 inch          4.3        inch             4.3
14     14         4.3 inch          4.3        inch             4.3
15     15              NaN                                     None
16     16              NaN                                     None
17     17              NaN                                     None
18     18              NaN                                     None
19     19       208.0 volt        208.0        volt           208.0

    is_not_float_or_null
0                  False
1                  False
2                  False
3                   True
4                   True
5                  False
6                  False
7                  False
8                  False
9                  False
10                  True
11                 False
12                 False
13                 False
14                 False
15                  True
16                  True
17                  True
18                  True
19                 False

In [56]:
df2.head(20)

,index,ans_entity_val,entity_value,entity_unit,processed_value,is_not_float_or_null
0,0,78.0 inch,78.0,inch,78.0,False
1,1,42.0 cm,42.0,centimetre,42.0,False
2,2,200.0 cm,200.0,centimetre,200.0,False
3,3,NaN,,,None,True
4,4,NaN,,,None,True
5,5,90.0 cm,90.0,centimetre,90.0,False
6,6,10.50 cm,10.50,centimetre,10.5,False
7,7,1.4 inch,1.4,inch,1.4,False
8,8,40.0 centimetre,40.0,centimetre,40.0,False
9,9,40.0 centimetre,40.0,centimetre,40.0,False
10,10,NaN,,,None,True
11,11,30.6 centimetre,30.6,centimetre,30.6,False
12,12,4.3 inch,4.3,inch,4.3,False
13,13,4.3 inch,4.3,inch,4.3,False
14,14,4.3 inch,4.3,inch,4.3,False
15,15,NaN,,,None,True
16,16,NaN,,,None,True
17,17,NaN,,,None,True
18,18,NaN,,,None,True
19,19,208.0 volt,208.0,volt,208.0,False

In [440]:
# print(df2.shape)
# print(len(df2['entity_unit'].unique()))
# print(df2['entity_unit'].unique())

# df2['entity_unit'].isnull().sum()

(131175, 4)
25
['inch' 'centimetre' nan 'volt' 'kilogram' 'pound' 'gram' 'millimetre' ''
 'ounce' 'metre' 'watt' 'ton' 'foot' 'millilitre' 'milligram' 'litre'
 'cup' 'kilowatt' 'quart' 'gallon' 'millivolt' 'yard' 'kilovolt' 'pint']

np.int64(47132)

In [441]:
# df2.drop(columns=['entity_value', 'entity_unit'], inplace=True)
# print(df2.shape)
# df2.head(20)

(131175, 2)

    index   ans_entity_val
0       0        78.0 inch
1       1          42.0 cm
2       2         200.0 cm
3       3              NaN
4       4              NaN
5       5          90.0 cm
6       6         10.50 cm
7       7         1.4 inch
8       8  40.0 centimetre
9       9  40.0 centimetre
10     10              NaN
11     11  30.6 centimetre
12     12         4.3 inch
13     13         4.3 inch
14     14         4.3 inch
15     15              NaN
16     16              NaN
17     17              NaN
18     18              NaN
19     19       208.0 volt

In [443]:
df2.to_csv('final_test_output_eda.csv', index=False)

In [58]:
df3= pd.read_csv('./dataset/test.csv')
print(df3.shape)
print(df2.shape)

(131187, 4)
(131175, 6)

In [445]:
df3.drop(columns=['image_link', 'entity_name', 'group_id'], inplace=True)
missing_indices = df3[~df3['index'].isin(df2['index'])]

# Create a DataFrame with these missing index values and set ans_entity_val to NaN
missing_rows = missing_indices[['index']].copy()
missing_rows['ans_entity_val'] = np.nan

# Append the missing rows to df2
df2 = pd.concat([df2, missing_rows], ignore_index=True).sort_values(by='index').reset_index(drop=True)

print(df2.shape)
print(df3.shape)

(131187, 2)
(131187, 1)

In [374]:
# Compare the values in the specified column
diff_rows = df3['index'] != df2['index']

# Count the number of different values
count_diff = diff_rows.sum()
print(count_diff)

0

In [447]:
df2 = df2.rename(columns={'ans_entity_val': 'prediction'})

In [448]:
df2.to_csv('final_test_output_eda2.csv', index=False)

In [450]:
pd.read_csv('final_test_output_eda2.csv')

         index  prediction
0            0   78.0 inch
1            1     42.0 cm
2            2    200.0 cm
3            3         NaN
4            4         NaN
...        ...         ...
131182  131283  1500 pound
131183  131284         NaN
131184  131285         NaN
131185  131286         NaN
131186  131287         NaN

[131187 rows x 2 columns]

In [452]:
# Create 'value' and 'unit' columns based on 'prediction'
df2['value'] = df2['prediction'].apply(lambda x: x.split(' ')[0] if isinstance(x, str) and ' ' in x else x if isinstance(x, str) else None)
df2['unit'] = df2['prediction'].apply(lambda x: x.split(' ')[1] if isinstance(x, str) and ' ' in x else None)

len(df2['unit'].unique())

355

In [454]:
df2['unit'] = df2['unit'].str.lower()
df2['unit'].unique()

array(['inch', 'cm', None, 'centimetre', 'volt', 'kilogram', 'pound',
       'gram', 'millimeter', 'millimetre', 'watt', 'ounce', 'mm', 'floz',
       'ton', '2.83inch', 'diameter', 'centimeter', 'foot', 'meter',
       'determine', 'millilitre', 'grams', 'milligram', 'oz', 'inches',
       'pounds', 'in', 'milliliter', 'bulb', 'numerical_value', 'litre',
       'cup', 'gramco', 'kilowatt', '110cm', '20.5cm', 'ithum', 'liter',
       'numerical', 'cm³', 'quart', 'hints', 'milligrams', 'metre', 'ml',
       '6cm', 'compact', 'lb', 'ampere', 'qt', 'b/m2', 'floz946ml',
       'mutant', 'gallon', 'mango', 'volts', 'lers/simples', 'gm', 'rpm',
       'mushroom', '5cm', 'ounces', 'bounces', 'gsm', 'softchews', '45cm',
       '1cm', 'kg', '30cm', 'floz330', '40mm', 'oz59ml', '150cm/59inch',
       '136mm', '300ml', 'millivolt', 'lbs', 'floz330ml', 'million',
       'fast-absorbing', 'cm²', '8.1in', '43mm/1.69inch', 'cm40.4',
       '20cm', 'amp', 'watts', 'government', '42cm', 'miom', 'carcam',
       'floz33ml', 'epsom', 'mile', 'cubic_inch', 'grammes',
       'millimetres', 'made', 'left', 'imported', 'mg', 'cfm/watt',
       'home', 'feet', 'floating_integer', 'lumens', '210cm', 'cms',
       'floz355', 'mah', 'milliampere-hour', 'tmakita', 'determined',
       'cm28.0', '13cm/5inch', 'cm3', 'umens', 'miles', 'cm24.8',
       'floz355ml', '6.7in', '3in', '3x3m', '7mm', '8mm', 'coins',
       '20.7cm/8.1', 'determinable', '0.1inch', 'me', 'centimetres',
       'kilograms', '14mm', 'ft', 'millimeters', '127mm', 'smartest',
       'times', 'm³', '178mm', 'integer', 'company', 'omato', '11.0cm',
       'from40-120lb', 'floz1p1473ml', 'singlebrgits', '90mm', 'meters',
       'compatible', 'g/m2', 'makita', 'micromillimeter', 'cfm', '87cm',
       '22cm/8.6in', '123cm', 'beam', 'morice', 'serving', '95mm',
       '0.7cm/0.27in', 'veodymiun', 'ml4oz', 'lumen', 'family', '52mm',
       'mic', 'micrometre', '29cm', 'r/min', 'qqty1', 'spin', 'm24',
       'microfarad', '22mm', 'centimeters', '28cm', '55mm', '60x200cm',
       'sinocmp', 'silber', 'lozenges', '3x5m', 'micrometer',
       'information', '24mm', 'mph', '55cm', 'nanogram', 'defined',
       '1.3inch', 'milliamp', 'milliampere', '15in', 'performancee',
       'decimal', '2.2inch', '4.0m', '12cm/4.72in', 'oz60', 'floz355m',
       'yard', 'ram', '2in', '2cm', 'oz80g', '8cm', '5in', 'mr.go',
       '17mm', 'complex', 'max', '2.5x2.5m', '41cm', 'choking', 'mrc',
       '60cm', 'moooon', '15mm', '24cm', 'm', '200cm', '24x19x8cm',
       'milliwatt', 'millile', 'cubic_meter', '2.5ft', 'mooe3-sntry',
       '19mm', '7in', 'ovelmp', 'coin', 'line', '150mm', '7cm', 'mm3',
       'gallons', 'kilometer', 'sunshine', 'cylinder', 'walimex',
       '5.19inch', 'millilitres', 'm3/h', '108inch', '31cm',
       '1500pcs85x50cm', '35mm/1.37in', 'planning', 'premier', 'mm³',
       '47mm71.85in', 'assembly', '1.7inch', 'yards', '100cm', 'more',
       'eadas-elbow', '54mm', 'lbtimkenload', 'mmlt', '5mm', 'flozcan',
       'gram/square_meter', '5.8in', '7.48in', 'smaller', '15cm/5.9in',
       'carmo', '8ohm/15vc', '115mm', '30ml', 'undefined', '227mm',
       'tomas', '60in', 'mil', '47cm', '11cm/4.33inch', '13cm/5.1in',
       '12*18inch', 'm711', 'makes', '6.35mm', '8m', 'mid', 'dome',
       'pump', 'input', 'mr-black', 'impedance', 'samsung', '100lbs',
       'minute', 'bocina', 'kilovolt', 'cubic_centimeter', 'gal',
       'minutes', 'millifloz', 'aluminum', 'megahertz', 'floz473ml',
       'floz1qt546m', 'oz1l', 'almond', 'medium', 'pint', 'oz59', 'mb',
       'servings', 'madefor', '186ml', 'csm', 'fl.oz6ml', 'sml',
       'oz355ml', 'ozhalf', 'ozhal', 'floz35ml', '8-inch', 'lozenge',
       'aquarium', 'floz710n', 'liters', 'floz1qt/946ml', 'yds/215m',
       'grain', 'floz472ml'], dtype=object)

In [86]:
df2= pd.read_csv("./final_test_output_eda_interm2.csv")
len(df2['entity_unit'].unique())

25

In [87]:
# Function to check if a value is not a float and not null
def is_not_float_or_null(value):
    if pd.isnull(value):
        return False
    try:
        float(value)
        return False
    except ValueError:
        return True

# Apply the function to filter rows
filtered_df = df2[df2['entity_value'].apply(is_not_float_or_null)]

print(filtered_df.shape)
filtered_df.head()

# Update the entity_value and entity_unit columns for the filtered rows
df2.loc[df2['entity_value'].apply(is_not_float_or_null), ['entity_value', 'entity_unit']] = ''

print(df2.shape)
df2.head(20)


# import pandas as pd

# # Function to check if a value is not a float or not null and to convert scientific notation to float
# def process_value(value):
#     if pd.isnull(value):
#         return None, True  # Return None to mark it as null
#     try:
#         # Convert value to float if it's a valid float (including scientific notation)
#         float_value = float(value)
#         return float_value, False  # Valid float, so not in the filtered list
#     except ValueError:
#         return value, True  # Not a float, so it should be in the filtered list

# # Apply the function to the 'entity_value' column
# df2[['processed_value', 'is_not_float_or_null']] = df2['entity_value'].apply(lambda x: pd.Series(process_value(x)))

# # Filter rows where 'is_not_float_or_null' is True
# filtered_df = df2[df2['is_not_float_or_null']]

# print(filtered_df.shape)
# print(filtered_df.head())

# # Update the 'entity_value' and 'entity_unit' columns for the filtered rows
# df2.loc[df2['is_not_float_or_null'], ['entity_value', 'entity_unit']] = ''

# print(df2.shape)
# print(df2.head(20))

(498, 4)
(131175, 4)

    index   ans_entity_val entity_value entity_unit
0       0        78.0 inch         78.0        inch
1       1          42.0 cm         42.0  centimetre
2       2         200.0 cm        200.0  centimetre
3       3              NaN          NaN         NaN
4       4              NaN          NaN         NaN
5       5          90.0 cm         90.0  centimetre
6       6         10.50 cm        10.50  centimetre
7       7         1.4 inch          1.4        inch
8       8  40.0 centimetre         40.0  centimetre
9       9  40.0 centimetre         40.0  centimetre
10     10              NaN          NaN         NaN
11     11  30.6 centimetre         30.6  centimetre
12     12         4.3 inch          4.3        inch
13     13         4.3 inch          4.3        inch
14     14         4.3 inch          4.3        inch
15     15              NaN          NaN         NaN
16     16              NaN          NaN         NaN
17     17              NaN          NaN         NaN
18     18              NaN          NaN         NaN
19     19       208.0 volt        208.0        volt

In [64]:
df2.head()

,index,ans_entity_val,entity_value,entity_unit,processed_value,is_not_float_or_null
0,0,78.0 inch,78.0,inch,78.0,False
1,1,42.0 cm,42.0,centimetre,42.0,False
2,2,200.0 cm,200.0,centimetre,200.0,False
3,3,NaN,,,None,True
4,4,NaN,,,None,True

In [89]:
df2['prediction'] = df2['entity_value'].astype(str) + ' ' + df2['entity_unit']
df2.drop(columns=['entity_value', 'entity_unit', 'ans_entity_val'], inplace=True)
df2.head(10)

   index        prediction
0      0         78.0 inch
1      1   42.0 centimetre
2      2  200.0 centimetre
3      3               NaN
4      4               NaN
5      5   90.0 centimetre
6      6  10.50 centimetre
7      7          1.4 inch
8      8   40.0 centimetre
9      9   40.0 centimetre

In [90]:
# df2.drop(columns=['is_not_float_or_null'], inplace=True)
# df2.head(10)

KeyError: "['is_not_float_or_null'] not found in axis"

In [69]:
df2['prediction'].replace({None: np.nan}, inplace=True)
df2.head()

   index        prediction
0      0         78.0 inch
1      1   42.0 centimetre
2      2  200.0 centimetre
3      3             None
4      4             None

In [91]:
df102= pd.read_csv('./dataset/test.csv')
print(df2.shape)
print(df102.shape)

(131175, 2)
(131187, 4)

In [92]:
# df102.drop(columns=['image_link', 'entity_name', 'group_id'], inplace=True)
missing_indices = df102[~df102['index'].isin(df2['index'])]

# Create a DataFrame with these missing index values and set ans_entity_val to NaN
missing_rows = missing_indices[['index']].copy()
missing_rows['prediction'] = np.nan

# Append the missing rows to df2
df2 = pd.concat([df2, missing_rows], ignore_index=True).sort_values(by='index').reset_index(drop=True)

print(df2.shape)
print(df102.shape)

(131187, 2)
(131187, 4)

In [93]:
df2.head()

   index        prediction
0      0         78.0 inch
1      1   42.0 centimetre
2      2  200.0 centimetre
3      3               NaN
4      4               NaN

In [76]:
df2.drop(columns=['ans_entity_val'], inplace=True)
df2.head()

   index        prediction
0      0         78.0 inch
1      1   42.0 centimetre
2      2  200.0 centimetre
3      3             None
4      4             None

In [94]:
print(df2.shape)
df2['prediction'].isnull().sum()

(131187, 2)

np.int64(46417)

In [81]:
df2['prediction']= df2['prediction'].replace({None: np.nan})
df2.head()

df2[df2['prediction']==None]

Empty DataFrame
Columns: [index, prediction]
Index: []

In [82]:
filtered_df = df2[pd.isnull(df2['prediction'])]

print(filtered_df)

         index prediction
35000    35042        NaN
37000    37044        NaN
51046    51093        NaN
70000    70064        NaN
107000  107076        NaN
112000  112079        NaN
116000  116080        NaN
119000  119080        NaN
122000  122092        NaN
125000  125096        NaN
128000  128098        NaN
131000  131101        NaN

In [95]:
df2.to_csv('final_test_output_eda15.csv', index=False)

KeyError: "['image_link', 'entity_name', 'group_id'] not found in axis"